### ISSUE TITLE
Mac OSX High Sierra and Psychtoolbox

### ISSUE THREAD

**Issue by amattek** [Psychtoolbox-3/Psychtoolbox-3#491] opened 2018-06-27 23:02 UTC
Hi,

I am troubleshooting a script that had been working fine on Sierra (albeit, sometimes it would throw a random error right at the beginning, but usually it would work on the second try).

Basically, the "Screen" function isn't working, and I get the following error:

The returned error message by Matlab/Octave was:
Last Error: Invalid MEX-file '/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64': Missing dependent shared libraries:
'/usr/local/lib/libdc1394.22.dylib' required by '/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64'

Given the previous issue posted and the comments concerning Apple's decision to phase out OpenGL support, is it a waste of time trying to troubleshoot this?

I noticed the recommendations to move to Linux. I personally have never used Linux, so I'm not sure what that learning curve is...I know this is kind of a basic question, but do you have any recommended resources for switching over to Linux? Can I run Linux on this Mac? Specs:
<img width="317" alt="screen shot 2018-06-27 at 3 51 41 pm" src="https://user-images.githubusercontent.com/26439600/42004200-af72c892-7a23-11e8-9412-83af42692f48.png">

Seems a little absurd to learn a whole new operating system just to run a MATLAB script. I would appreciate any recommendations...thank you!!

**Comment by yhz-1995** [comment] 2018-07-02 02:02
Well although I don't have much experience with Mac, I guess linux and mac shouldn't be that much different compared to linux and windows. Both of them are Unix-based systems.

**Comment by yhz-1995** [comment] 2018-07-02 02:07
Linux distros like Ubuntu have a LiveCD mode. You can write the iso file to a USB flash stick, insert to your computer, reboot and boot from the USB stick, and try Ubuntu WITHOUT ANY CHANGES to your original system.

**Comment by kleinerm** [comment] 2018-07-02 15:13
Wrt. Linux, on suitable hardware, in general i don't think it is very difficult to learn how to use a modern distribution like Ubuntu 18.04-LTS for day to day use, or for use with PTB, depending on your general computer skills. I know enough interns, bachelor and master students, and grad students who were easily able to install it and set it up, without any assistance from myself. I think it is mostly about attitude and willingness to adapt -- Resistance to learn seems to be a much bigger problem with many Mac users due to the widespread religious devotion to the iPhone company.

However, in your case it would be pretty challenging to install Linux as a beginner, as Apple's latest MacBook(Pro) models (at least the 2015/16/17 models) are designed to be rather hostile to alternative operating systems, so Linux is not expected to work well without substantial tweaking, which would probably be a steep learning curve. The current state of your machine (MacBookPro14,2) is not so great: No wifi, no suspend/sleep/resume for the laptop, no sound unless using an external USB sound card, keyboard/touchpad/touchbar only working after manual installation of a 3rd party driver - which requires some skills in operating a terminal. So i'd say you'd have to wait a bit longer until all this stuff works out of the box, or prepare for quite a bit of tinkering and learning.

That said, OpenGL will probably continue to "work" in its current sorry state for a while, so as long as you don't need precisely timed visual stimulation (errors < +-1-2 refresh durations < 33 msecs) or reliably correct gamma calibration etc., and it worked so far for you, you can still use macOS for the time being, although you should make friendship with Linux, with a different machine, or once it works on your laptop. Timing precision/reliability on older machines with Intel graphics was never super-trustworthy or accurate on macOS, although it es excellent with intel gfx on Linux -- one of many limitations of macOS.

I don't think it is even a little bit absurd to use the right tool for the job. If you want to do reproducible science and your paradigms require high precision and robustness/trustworthiness of visual stimulation, or reliable digital/analog i/o, or sometimes reliable response collection, then macOS has been the wrong choice for at least the last 5 years, and with Apples deprecation of OpenGL the future isn't looking good. Of course not every paradigm needs very high precision, so maybe your stimuli are "high level" enough so that even a crippled macOS is still perfectly fine. If somebody shows natural pictures for a second, and doesn't measure reaction times, an error of 30 msecs probably won't matter much, or playing back a video without any requirements for measuring reaction times or other precise timing, as long as audio-video lip-sync is still acceptable, again a couple of dozen msecs error is probably ok.

But more to the concrete problem you see, this error isn't something that is expected to happen, and in fact i have not ever seen a report of such a failure, even though we have more than 1000 users on 10.13, so something must be weird on your machine. It says it is missing  '/usr/local/lib/libdc1394.22.dylib' required by '/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64', but libdc1394.22.dylib is *optional* for use of Screen on macOS. If you don't have it, some high performance firewire video capture/recording functionality is disabled, but other than that, Screen should work fine.

What version of Matlab is this?

From a terminal, what is the output of "otool -L /Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64"?

You can try installing that library by reading "help VideoCaptureDC1394" / simply executing VideoCaptureDC1394 and see if that solves the problem or gives a different error message.

**Comment by amattek** [comment] 2018-07-03 01:10
Thank you so much for your in depth replies, this is extremely helpful! I do have some interest in learning Linux if need be, but your comments about that potentially being difficult with this particular computer are very helpful. From what you said, it seems like if I'm going to move to Linux, it might be more advisable to do so on a Windows machine.

The version of MATLAB is 2017. We were using 2018 but were getting GStreamer errors that we had trouble fixing, and thought reverting to an older version of MATLAB that was used to code the script originally might be a fix. 

The dylib file that it tells me I'm missing is actually not missing, but for some reason the program just can't find it. I am away from the lab for a few days, but I'll try the troubleshooting options you described when I get back and let you know if I resolve things.

The particular stimuli I'm working with are actually high level enough that I don't need super precise timing, so it's good to know that the issues we are having can potentially be resolved.

Again, thank you so much for your input, I'll will post again with an update shortly!

**Comment by kleinerm** [comment] 2018-08-20 15:17
No new updates in over a month. Closing.

**Closed by kleinerm** 2018-08-20 15:17 UTC
