### ISSUE TITLE
Compatibility with OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by shandelman116** [Psychtoolbox-3/Psychtoolbox-3#214] opened 2014-10-21 18:40 UTC
I just got a new MacBook Pro and I am running Yosemite and it seems like Psychtoolbox-3 is not fully compatible... When can we expect an update to make psychtoolbox compatible? Thanks.

**Comment by mattrjohnson** [comment] 2015-01-02 03:23
+1 to Mario's solution that plugging in an external monitor (even if you then unplug it again before ever running Matlab/PTB) solves the issue enough to pass sync tests. (This is on a mid-2012 MacBook Air, Intel graphics, no Retina display.) Certainly not ideal, but good enough for my own usage cases.

**Comment by kcrowley1** [comment] 2015-01-05 10:46
Sorry! Full error here:
<script src="https://gist.github.com/kcrowley1/0b8a0e70bfb847e41b5f.js"></script>

Thanks for the external monitor advice!

**Comment by iandol** [comment] 2015-01-06 13:30
Are you sure you've set SkipSyncTests > 0, as that output suggests otherwise.

**Comment by kcrowley1** [comment] 2015-01-27 17:01
Hi all, 

Sincere apologies about the delay in getting back to you on this - other fires to put out etc! 

So I have tried the external monitor, again running OSXCompositorIdiocyTest() but no luck with that either. 

@iandol I followed the necessary steps and *thought* I had - followed the instructions as per the help docs - I must be missing something! 

Here is what I get now:

```
>> OSXCompositorIdiocyTest()


PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Nov  5 2014).
PTB-INFO: Support status on this operating system release: OSX 10.10 Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Always using Cocoa for fullscreen windows to work around graphics driver bugs in OSX.
PTB-INFO: Presentation timing precision is not yet known for this configuration on most machines. Check your results.


PTB-INFO: You are using a multi-display setup (2 active displays):
PTB-INFO: Please read 'help MultiDisplaySetups' for specific information on the Do's, Dont's,
PTB-INFO: and possible causes of trouble and how to diagnose and resolve them.

PTB-INFO: According to the operating system, some of your connected displays do not seem to 
PTB-INFO: be switched into mirror mode. For a discussion of mirror mode vs. non-mirror mode,
PTB-INFO: please read 'help MirrorMode'.


PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel HD Graphics 5000 OpenGL Engine :: 2.1 INTEL-10.0.86
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 1050 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.680880 ms [59.948874 Hz]. (296 valid samples taken, stddev=0.720398 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?


----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.


Error using Screen
See error message printed above.

Error in OSXCompositorIdiocyTest (line 67)
  win = Screen('Openwindow', testScreen, 0);
```

Sorry about the n00b-ness! Thought it would be a straightforward matter to get the toolbox running for development purposes. Thanks for the help.

**Comment by kcrowley1** [comment] 2015-01-27 17:22
Not sure if this helps - but I just unloaded and deleted the driver again and tried re-installing PsychtoolboxKernelDriver.kext again. 

I get:
```
kcrowley$ kextstat -b PsychtoolboxKernelDriver
Index Refs Address            Size       Wired      Name (Version) <Linked Against>
   85    0 0xffffff7f80de8000 0xa000     0xa000     PsychtoolboxKernelDriver (1.1) <12 4 3>
```

I then followed the instructions in the help file again- rebooted, cleared the Screen and added *Screen('Preference', 'SkipSyncTests', 1);* to the top of the 'demo1' script, as advised. I ran it again and got:

```
>> clear Screen
>> demo1
PTB-INFO: Connection to Psychtoolbox kernel support driver instance #0 (Revision 1) established.
PTB-INFO: Disconnecting from kernel driver instance #0 for detected Intel GPU for safety reasons. setenv('PSYCH_ALLOW_DANGEROUS', '1') to override.
PTB-INFO: Running on OSX 10.9+ - Enabling protection against AppNap and other evils.
PTB-INFO: Connection to Psychtoolbox kernel support driver instance #0 (Revision 1) established.
PTB-INFO: Disconnecting from kernel driver instance #0 for detected Intel GPU for safety reasons. setenv('PSYCH_ALLOW_DANGEROUS', '1') to override.
PTB-INFO: Running on OSX 10.9+ - Enabling protection against AppNap and other evils.


PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Nov  5 2014).
PTB-INFO: Support status on this operating system release: OSX 10.10 Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Always using Cocoa for fullscreen windows to work around graphics driver bugs in OSX.
PTB-INFO: Presentation timing precision is not yet known for this configuration on most machines. Check your results.


PTB-INFO: You are using a multi-display setup (2 active displays):
PTB-INFO: Please read 'help MultiDisplaySetups' for specific information on the Do's, Dont's,
PTB-INFO: and possible causes of trouble and how to diagnose and resolve them.

PTB-INFO: According to the operating system, some of your connected displays do not seem to 
PTB-INFO: be switched into mirror mode. For a discussion of mirror mode vs. non-mirror mode,
PTB-INFO: please read 'help MirrorMode'.


PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel HD Graphics 5000 OpenGL Engine :: 2.1 INTEL-10.0.86
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 1050 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.679045 ms [59.955473 Hz]. (295 valid samples taken, stddev=0.795141 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?


----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.


Error using Screen
See error message printed above.

Error in PsychImaging (line 1913)
            [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode,
            multiSample, imagingMode, specialFlags, clientRect);

Error in demo1 (line 31)
[window, windowRect] = PsychImaging('OpenWindow', screenNumber, grey);
```

**Comment by dxjones** [comment] 2015-01-27 22:43
Hi,

You're getting kicked out because the VBLsync during startup sees the
stddev is 0.72 msec, which it concludes is too large and it aborts.

A potential workaround is to skip this test.

Screen('Preference','SkipSyncTests',1);

This will at least get you further, though you may encounter another issue.


I would also invite you to try my code here:

    https://github.com/dxjones/MeasureFlipInterval

Try running it like this:  (which skips the VBL Sync Test at startup)

    MeasureFlipInterval(1)

I have never run my code on a system that PTB claims has no beam position
queries, so I am curious to see what happens on your machine.
Please cut-and-paste your timing results from the command window and send
them to me by email.

-- David Jones

**Comment by kleinerm** [comment] 2015-01-28 05:00
@kcrowley1 please ignore what @dxjones told you. He has conclusively proven that he doesn't even have the most rudimentary understanding of the issue, but an impressive amount of confidence into his understanding of the issue. It would be nicer if he would only potentially ruin his own work, as sad as that would be, and not try to also ruin others work as well by giving utterly misguided advice, or waste my time by just not taking any input:

Here is the relevant thread on the Psychtoolbox forum - or one of them - marvel at the mindblowing reasoning in there:

https://groups.yahoo.com/neo/groups/PSYCHTOOLBOX/conversations/messages/18629

I considered deleting his misguided advice, but sometimes bad examples are also something one can learn of.

Apart from the measures explained otherwise in this GitHub issue conversation, one thing that might work on your Intel HD-5000 gpu is to switch the resolution of your display to some random video mode (ie. not the default resolution) and then after a few seconds back to its original setting. That forth-and-back switch seems to potentially temporarily "fix" the problem on at least a few OSX machines *until the machine is rebooted* in which case you have to rinse, wash & repeat.

You should run OSXCompositorIdiocyTest after confirming the above hack helped to get rid of the sync failures as another measure of caution. If you really care about timing you should also *always* verify your setup at least once with external hardware measurement equipment like photo-diodes, Datapixx devices etc. after each hardware or operating system upgrade.

I haven't tested the one macMini on which this video mode switching hack worked with external measurement equipment, because i a) don't have time for it atm. and b) there are various other bugs in current OSX which make it sometimes impossible, sometimes painful to even use said measurement equipment properly.

So be extra cautious. It's a good trait for a scientist, but especially important when dealing with current OSX versions.

-mario

**Comment by kcrowley1** [comment] 2015-01-28 11:19
Thanks Mario! The hack worked :-) Very much appreciated! 

I will be using a different machine for testing that has been thoroughly tested - this is just for development! 

Delighted to have this sorted, thank you!

**Comment by FuZhiyu** [comment] 2015-03-17 15:38
Mario, I specially sign up to give a thank to you!!
Very appreciated!
How does this hack works? It seems like a magic!

**Comment by kleinerm** [comment] 2015-03-17 20:14
It works because two separate OSX bugs cancel each other out. The 2nd bug is triggered by the resolution switching and keeps the first one in check. Iow., it works because OSX is a broken operating system, and it is indeed magic in the sense of being random and unpredictable, and that is a bad sign for  a system that is intended to be used for reproducible research.

Thank yous are best expressed by donations, btw., as they are the thing that keeps the lights on and thereby makes the magic continue ;-)

http://psychtoolbox.org/donations/

**Comment by FuZhiyu** [comment] 2015-03-18 03:19
I’m so sorry. I tried but failed to find the way to donate. I'm in China and as a student I don’t have a Credit Cardπ_π

**Comment by FuZhiyu** [comment] 2015-03-19 06:51
@kleinerm Unfortunately, it worked well when running a Demo, but failed with a bigger program. My friends told me it also failed on Win7 (the laptop is Lenovo v480s). 
I'm wondering if I choose to skip the SyncTest, will it impair the timing accuracy to a unbearable extent?

**Comment by kleinerm** [comment] 2015-03-19 15:40
I don't know what you mean? This issue is about bugs and problems and solutions specific to Yosemite, so obviously the same failure can't happen on Win7, unless you mean something not directly related to Yosemite, just something else that causes sync failure - there are many reasons. Synctests fail on systems with bad timing, broken timing or some other issues related to getting pixels onto the screen. You'd have to check the user forum, FAQ's, help texts of PTB etc. to see why it happens on your setup and what to do about it. Have you checked the Psychtoolbox forums, "help SyncTrouble" etc.?

Btw. wrt. donations, don't worry, i don't expect students to donate their usually already scarce money. But if labs or PI's etc. can afford to donate a bit, that's appreciated. Nobody has to donate, but if not enough people will donate, it will simply mean that i'll have to turn much of my now free work into paid work - which will be much more expensive to anybody who needs my help than small donations.

**Comment by nauders** [comment] 2015-04-28 22:33
Hi Mario and all,

I am testing Psychtoolbox on my new setup and I would like to get some feedback (questions below).

My setup is as follows:
Macbook Pro Retina Display
OSX 10 Yosemite
Retina display
Matlab R2015a
Psychtoolbox Version 3.0.12
PsychtoolboxKernelDriver64Bit.kext installed
Single screen mode

I opened Matlab and launched VBLSyncTest. I was expecting to get a sync error, which I actually got:

```
>VBLSyncTest

PTB-INFO: Connection to Psychtoolbox kernel support driver instance #0 (Revision 1) established.
PTB-INFO: Disconnecting from kernel driver instance #0 for detected Intel GPU for safety reasons. setenv('PSYCH_ALLOW_DANGEROUS', '1') to override.
PTB-INFO: Running on OSX 10.9+ - Enabling protection against AppNap and other evils.

ans =

    0

PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Apr 18 2015).
PTB-INFO: Support status on this operating system release: OSX 10.10 Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Always using Cocoa for fullscreen windows to work around graphics driver bugs in OSX.
PTB-INFO: Presentation timing precision is not yet known for this configuration on most machines. Check your results.

PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel Iris OpenGL Engine :: 2.1 INTEL-10.6.20
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 1600 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.644721 ms [60.079110 Hz]. (298 valid samples taken, stddev=1.002851 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----
```

So it seems that it's not using the PsychtoolboxKernelDrivers, which is also expected since this laptop has an Intel graphic card.
As I see from the output, stddev is about 1 ms. First question: Suppose for my purposes I am fine with a 1 ms uncertainty/variability. May I just skip sync test and trust my timestamps thereafter (keeping in mind the ~1ms uncertainty)?
Then, I was interested in testing whether I could get better timing anyways. So I followed Mario's advice and did the trick of connecting and disconnecting an external monitor.
I ran VBLSyncTest again, got no sync error, and the test was executed. This is the output code:

```
>VBLSyncTest

PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Apr 18 2015).
PTB-INFO: Support status on this operating system release: OSX 10.10 Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Always using Cocoa for fullscreen windows to work around graphics driver bugs in OSX.
PTB-INFO: Presentation timing precision is not yet known for this configuration on most machines. Check your results.


PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel Iris OpenGL Engine :: 2.1 INTEL-10.6.20
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 1600 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.676308 ms [59.965310 Hz]. (50 valid samples taken, stddev=0.054714 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 33793 ...
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus drawing.
PTB-INFO: Enabling panel fitter. Providing virtual framebuffer of 1280 x 800 pixels size.
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus post-processing (if any).
The refresh interval reported by the operating system is 16.66667 ms.
Measured refresh interval, as reported by "GetFlipInterval" is 16.67631 ms. (nsamples = 0, stddev = 0.00000 ms)

ans =

    9.0000

INFO: PTB's Screen('Flip', 10) command seems to have missed the requested stimulus presentation deadline
INFO: a total of 2 times out of a total of 605 flips during this session.

INFO: This number is fairly accurate (and indicative of real timing problems in your own code or your system)
INFO: if you provided requested stimulus onset times with the 'when' argument of Screen('Flip', window [, when]);
INFO: If you called Screen('Flip', window); without the 'when' argument, this count is more of a ''mild'' indicator
INFO: of timing behaviour than a hard reliable measurement. Large numbers may indicate problems and should at least
INFO: deserve your closer attention. Cfe. 'help SyncTrouble', the FAQ section at www.psychtoolbox.org and the
INFO: examples in the PDF presentation in PsychDocumentation/Psychtoolbox3-Slides.pdf for more info and timing tips.

PTB missed 1 out of 600 stimulus presentation deadlines.
One missed deadline is ok and an artifact of the measurement.
PTB completed 0 stimulus presentations before the requested target time.
```

Okay, so stddev is much smaller now, which is nice. I am not sure if there are any other improvements that I didn't notice. Then, as Mario recommended on the forum, I decided to make a different test and run OSXCompositorIdiocyTest. This is the output:

```
> OSXCompositorIdiocyTest

PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Apr 18 2015).
PTB-INFO: Support status on this operating system release: OSX 10.10 Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Always using Cocoa for fullscreen windows to work around graphics driver bugs in OSX.
PTB-INFO: Presentation timing precision is not yet known for this configuration on most machines. Check your results.

PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel Iris OpenGL Engine :: 2.1 INTEL-10.6.20
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 1600 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.676303 ms [59.965331 Hz]. (50 valid samples taken, stddev=0.063351 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 33793 ...
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus drawing.
PTB-INFO: Enabling panel fitter. Providing virtual framebuffer of 1280 x 800 pixels size.
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus post-processing (if any).
Bye!
```
Again, there was no sync error, but I quite alarmed because I did not see any flicker at all (not at PASS I and not at PASS II). Does this mean there are still some issues with my setup that the trick of connecting/disconnecting an external monitor did not solve? And what kind of issues? Are there any workarounds?
Finally, I ran PerceptualVBLSyncTest and saw the flicker all the time.
I apologize if these questions appear very naive, but I am confused about what's behind the OSXCompositorIdiocyTest, and eventually I am unsure about the conclusion I can draw on the reliability of my current setup.

I am willing to run any more tests (if requested), and would appreciate any inputs/comments.

Thanks,
Francesco

Francesco Marini
Post-doctoral Research Associate
Dept. of Psychology, UC San Diego

**Comment by kleinerm** [comment] 2015-04-29 17:01
Try this updated OSXCompositorIdiocyTest.m file:

https://github.com/kleinerm/Psychtoolbox-3/raw/master/Psychtoolbox/PsychTests/OSXCompositorIdiocyTest.m

It needed an update to cope with Retina displays, otherwise it would report false failures due to the way it works with our new Retina support. If the new file flickers properly then your setup is probably ok. Another way of getting timing ok'ish is by switching video resolution force and back - that's a bit less annoying than connecting and disconnecting a 2nd display. In general high precision timestamping and various built-in correctness tests and workarounds for problems don't work anymore on Intel cards on OSX, so some graphics bugs would go unnoticed and timing precision will be lower/less robust, so only testing with a photo-diode or other equipment with your own scripts during data collection could give you confidence that everything worked. Only switching to Linux could improve on that. But iff the new test flickers, it is probably ok - we just can't test any further in software if there would be other problems. You could run VBLSyncTest(300, x) with x = 0, 1, 2 or 3 to test timed stimulation further in software, that's something i usually do.

**Comment by nauders** [comment] 2015-04-29 19:33
Mario, thanks much for the updated OSXCompositorIdiocyTest and for the video resolution switch trick.
The resolution switch trick worked just fine and I got rid of the Sync error.
The new OSXCompositorIdiocyTest worked great as well (I'm saying this because I saw the flicker during both passes). The difference I noticed with the old (non flickering) version is just that the text (PASS I... PASS II... etc.) was much smaller with the newer version. The output is below:

```
>> OSXCompositorIdiocyTest


PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Apr 18 2015).
PTB-INFO: Support status on this operating system release: OSX 10.10 Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Always using Cocoa for fullscreen windows to work around graphics driver bugs in OSX.
PTB-INFO: Presentation timing precision is not yet known for this configuration on most machines. Check your results.


PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel Iris OpenGL Engine :: 2.1 INTEL-10.6.20
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 1600 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.674692 ms [59.971122 Hz]. (50 valid samples taken, stddev=0.059836 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 263168 ...
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus drawing.
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus post-processing (if any).
Bye!
```

Then, as you suggested, I ran (various times):
```VBLSyncTest(300, x) with x = 0, 1, 2 or 3```
I observed: a very brief presentation of some text at the screen top (way too brief to be readable), no flicker with any x (was it supposed to flicker?), decreasing speed of the moving square as x increased, and reported misses of the stimulus presentation deadline as follows: 2 misses for x=0, 1 miss for x=1, and 0 misses for x>=2. I suppose this is a fairly good result although I'd appreciate if you might confirm.

Thanks again for your help and advice.

Francesco

**Comment by kleinerm** [comment] 2015-04-30 00:34
That's all fine. The smaller text size is because the test now works at the true resolution of the retina panel, not the lower compatibility mode resolution. Compatibility mode caused the false results of the test.

**Comment by kleinerm** [comment] 2015-12-08 02:17
Closing, as we no longer care or officially support 10.10.

**Closed by kleinerm** 2015-12-08 02:17 UTC
Labels: question

**Comment by enoche12** [comment] 2018-11-26 16:15
>> ScreenTest

***** ScreenTest: Testing Screen 0 *****


PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.15 - Build date: Oct 19 2018).
PTB-INFO: Support status on this operating system release: Windows 10 (Version 10.0) supported and tested to some limited degree.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

WARNING: VBL Calibration run No. 1 failed. Retrying...
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

WARNING: VBL Calibration run No. 2 failed. Retrying...
WARNING: Will enable VBL busywait-workaround before trying final VBL Calibration run No. 3.
WARNING: This will hopefully work-around graphics driver bugs of the GPU sync-to-retrace mechanism. Cross your fingers!
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.


PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: AMD Radeon R7 Graphics :: 4.5.13467 Compatibility Profile Context 21.19.414.1280
PTB-INFO: VBL startline = 768 , VBL Endline = 795
PTB-INFO: Measured monitor refresh interval from beamposition = 16.666170 ms [60.001787 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 0.000000 ms [inf Hz]. (0 valid samples taken, stddev=10000000.000000 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

WARNING: Mismatch between measured monitor refresh interval and interval reported by operating system.
This indicates massive problems with VBL sync.


----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.


Error using Screen
See error message printed above.

Error in ScreenTest (line 15)
    w = Screen('OpenWindow',screen);
 
>> my laptoptop is hp,windows 10 AMD RADEON R7 64 BIT OPERATING SYSTEM

**Comment by iandol** [comment] 2018-11-27 00:15
@enoche12 — did you carefully read `help SyncTrouble` as the PTB error message asked you? Also this (closed) issue has nothing to do with you generic error.
