### ISSUE TITLE
Audio output from user input delays

### ISSUE THREAD

**Issue by AlexLepauvre** [Psychtoolbox-3/Psychtoolbox-3#667] opened 2020-05-28 19:32 UTC
Dear all,

We are preparing an experiment for which we need an audio trigger to be sent when participants hit the response key. The trigger that is being sent consists of a 9 bit code, composed of squared waves. Such triggers are being sent to mark events (stimuli onsets and response onsets) in neural signal, because we cannot rely on standard hardware. While the audio triggers work totally fine for the stimuli onsets (see the attached image 1), they do not for most (more than half) the response ones (see image 2). As you can see in image 2, there seems to be half a bit being sent, followed by an interruption, and the rest of the trigger only comes after this interruption. The most logical explanation based on the implementation of the code (see below) is that the playback of the audio buffer is actually interrupted, as if the execution was being paused for a given time. It is really unclear to us why that is the case. However, it seems to be something related to the keyboard input. In the regular mode of the experiment, the priority is set to 1. However, when the priority is set to 0, then the problem doesn't appear anymore, which seems to indicate that when setting priority to 1, execution get interrupted after keyboard input. When looking at the Psychtoolbox documentation, I couldn't find a satisfying explanation of what might explain this strange behavior. But more importantly, it is really unclear to me what setting the priority to 0 entails. I therefore have three questions:
1. What is causing this interruption of playback when priority is set to 1?
2. Is it possible to get rid of this interruption while letting the priority on 1?
3. If not, what are the consequences of running the experiment on priority 0?

We really need the audio triggers to work as flawlessly as possible, but if the setting of priority to 0 impacts our timing, it will be really hard decision to make. 
The script is run in PTB-3 on windows 10. The audio driver is: Realtek High Definition

![Good trigger](https://user-images.githubusercontent.com/54275933/83183929-f9353900-a128-11ea-8408-268817394ef4.PNG)
![bad trigger](https://user-images.githubusercontent.com/54275933/83183941-fb979300-a128-11ea-80b4-c749a397ef66.PNG)

The code sending the triggers is as follows: 
`% SENDTRIGAUDIO
% Send a bit code trigger through the adio port
function [] = sendTrigAudio(trig_code_binary)

    % These variables are for debugging
    global triggersAudio 
    global pahandle
    global zerowave squarewave
    global triggsAudioCounter
    if VERBOSE disp('Into sendTrigAudio'); end
    if VERBOSE display(triggersAudio,'triggersAudio beginning of sendTrigAudio'); en
    
    
    % Adding a 1 in the beginning to communicate we're starting the code
    audio_trigger = squarewave;
    % Consruct the trigger wave:
    for bit_ind = 1:size(trig_code_binary,2)
        %if VERBOSE disp(bit_ind); end
        wave = squarewave;
        bit = trig_code_binary(bit_ind);
        if bit == '0'
            wave = zerowave;
        end % for
        if VERBOSE disp(size(audio_trigger)); end
        audio_trigger =  [audio_trigger; wave]; 
        
    end % end for
    
    % Adding a 1 at the end to indicate the end of the code
    audio_trigger = [audio_trigger; squarewave];
    
    % For debugging: Make sure this looks the same:
    %save MyAudiotrigger.mat audio_trigger;
    
    PsychPortAudio('FillBuffer', pahandle, audio_trigger');
    % %play sound in port
    AudioTimeStamp = PsychPortAudio('Start',pahandle, 1, 0);
    % Handling the timing like advised above triggers
    % Commeting this out now so that the program will continue while the
    % sound is being played
    %[actual_start_time, ~, ~, estStopTime] = PsychPortAudio('Stop', pahandle, 1, 1);
    %if VERBOSE display(actual_start_time, 'startTime'); end
    
     %triggsAudioCounter = triggsAudioCounter + 1;
     %triggersAudioTimes(triggsAudioCounter,2) = actual_start_time - triggsAudioStart;
    % Storing the triggers to the trigersAudio Matrix:
     triggersAudio{triggsAudioCounter,1} = cellstr(trig_code_binary);
     triggersAudio{triggsAudioCounter,2} = AudioTimeStamp;
   
     
     triggsAudioCounter = triggsAudioCounter+1;
     
     if VERBOSE 
        display(triggersAudio,'triggersAudio');
         disp('end of sendTrigAudio');
     end  
   
end`

This function is being called within a loop where the events occur at the set timings. At each iterations of the loop, the input is checked, and if there is an input, the response audio trigger is being sent.

Thanks in advance for your support,

Kind regards,

Alex

**Comment by AlexLepauvre** [comment] 2020-05-28 22:04
The function used to check input is KbCheck

**Comment by kleinerm** [comment] 2020-05-30 03:11
This is the latest up to date ptb 3.0.16, right?

Do the timestamps returned make sense? You can get all those also via PsychPortAudio('Status') a bit later if you don't want to do blocking waits. What is the 'xruns' variable reporting?

How does the PsychPortAudio('Open') call look like? What hardware is this?

Priority(1) sets the scheduling priority of the main thread to a higher than normal priority. But the PsychPortAudio driver also sets the scheduling priority of its audio processing thread to increased priority, especially if you set the reqlatencyclass parameter in 'Open' to a higher value like 2 or 3. So all should be good.

If these time delays are caused by Priority() it would point into the audio processing thread somehow starving of cpu time, but then you should also here audio artifacts, and possibly a non-zero 'xruns' count. And on modern multi-core processors this kind of starvation is quite unlikely.

**Comment by kleinerm** [comment] 2020-07-03 16:57
No feedback in over a month. Closing.

**Closed by kleinerm** 2020-07-03 16:57 UTC
