### ISSUE TITLE
Screen('OpenWindow',...) hangs indefinitely on Ubuntu 21.04 Wayland

### ISSUE THREAD

**Issue by JDrewes** [Psychtoolbox-3/Psychtoolbox-3#721] opened 2021-05-27 10:01 UTC
**Describe the bug**

I have two Linux development systems which I use to write my experiments on. They are then run for data collection on a different system (not involved here).

On Ubuntu 20.10, both systems ran fine (using intel graphics on one, intel/nvidia hybrid on the other).
Since I updated them to 21.04, PTB hangs indefinitely when calling Screen 'OpenWindow', regardless of wether the intention is fullscreen or windowed. In both cases, the selected screen area gets blackened out (even if a non-black background color was given as parameter), and the call to Screen never returns. CTRL-C doesn't work (just prints the control characters on the command line), kill doesn't work, I need to kill -9 to quit octave.  
I tried GNU Octave in the following versions:
6.1.1 as delivered with Ubuntu 21.04
6.2.0 as delivered with current Debian
5.2.0 as delivered with Ubuntu 20.10

This happens only when using Wayland (IsWayland=1), it works when using XOrg.

Cheers,
Jan

**To Reproduce**
boot Ubuntu 21.04, start octave, call Screen('OpenWindow',[some parameters])

**Expected behavior**
A window should open, and Screen(...) should return the handle.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 21.04
 - Runtime: Octave 5.2, 6.1.1, 6.2.0
 - Hardware Intel i7 Coffee Lake, Intel graphics (also happens on intel/nvidia hybrid in intel-only-mode and nvidia-only-mode)
 
On the Intel-only system, setting PTB verbosity to 5, I get the following output when calling Screen 'OpenWindow':

RandR: 1920x1080 (0x25)  173.0MHz
        h: width  1920 start 2048 end 2248 total 2576 skew    0
        v: height 1080 start 1083 end 1088 total 1120

PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under GNU/Octave 64-Bit (Version 3.0.17 - Build date: May 12 2021).
PTB-INFO: OS support status: Linux 5.11.0-17-generic Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: For information about paid priority support, community membership and commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.

PTB-DEBUG: Checking PCI device [Intel Corporation 8th/9th Gen Core 8-core Desktop Processor Host Bridge/DRAM Registers [Coffee Lake S]] with class x00060000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630]] with class x00030000 ...
PTB-INFO: Skipping detected Intel GPU for safety reasons. setenv('PSYCH_ALLOW_DANGEROUS', '1') to override.
PTB-DEBUG: Checking PCI device [Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model] with class x00088000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH Thermal Controller] with class x00118000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller] with class x000c0330 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH Shared SRAM] with class x00050000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0] with class x000c8000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH HECI Controller] with class x00078000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH SATA AHCI Controller] with class x00010601 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH PCI Express Root Port #17] with class x00060400 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH PCI Express Root Port #9] with class x00060400 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH PCI Express Root Port #11] with class x00060400 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Point-LP LPC Controller] with class x00060100 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH cAVS] with class x00040300 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH SMBus Controller] with class x000c0500 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Cannon Lake PCH SPI Controller] with class x000c8000 ...
PTB-DEBUG: Checking PCI device [Intel Corporation Ethernet Connection (7) I219-LM] with class x00020000 ...
PTB-DEBUG: Checking PCI device [Silicon Motion, Inc. SM2262/SM2262EN SSD Controller] with class x00010802 ...
PTB-DEBUG: Checking PCI device [ASMedia Technology Inc. ASM1083/1085 PCIe to PCI Bridge] with class x00060400 ...
PTB-INFO: No low-level controllable GPU on screenId 0. Beamposition timestamping and other special functions disabled.
PTB-INFO: Using old-style override-redirect (=1) setup path for onscreen window creation.
PTB-INFO: GLX Visual info depths is 24 bits
PTB-INFO: Running on Mesa version 21.0.1
PTB-INFO: This combo of X-Server and Mesa is considered safe for use under DRI3/Present.
PTB-INFO: Using GLEW version 2.1.0 for automatic detection of OpenGL extensions...
PTB-INFO: Window uses DRI3/Present for visual stimulus presentation.
PTB-INFO: Many graphics cards do not support proper timing and timestamping of visual stimulus onset
PTB-INFO: when running in windowed mode (non-fullscreen). If PTB aborts with 'Synchronization failure'
PTB-INFO: you can disable the sync test via call to Screen('Preference', 'SkipSyncTests', 2); .
PTB-INFO: You won't get proper stimulus onset timestamps though, so windowed mode may be of limited use.
PTB-INFO: Using GLX_MESA_swap_control extension for control of vsync.
PTB-INFO: Disabling VRR Variable Refresh Rate mode for this fullscreen window on Mesa graphics driver.
PTB-INFO: INTEL_swap_event support for additional swap completion correctness checks enabled.
PTB-INFO: Fixed point precision integer framebuffer enabled.
PTB-INFO: System Frame buffer provides 8 bits for red channel.
PTB-INFO: System Frame buffer provides 8 bits for green channel.
PTB-INFO: System Frame buffer provides 8 bits for blue channel.
PTB-INFO: System frame buffer provides 8 bits for alpha channel, but effective alpha bits depends on imaging pipeline setup, if any.

OpenGL-Vendor / renderer / version are: Intel - Mesa Intel(R) UHD Graphics 630 (CFL GT2) - 4.6 (Compatibility Profile) Mesa 21.0.1

OpenGL-Extensions are: GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_direct_state_access GL_EXT_vertex_attrib_64bit GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_fragment_shader_interlock GL_ARB_gpu_shader_int64 GL_ARB_parallel_shader_compile GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_ARB_gl_spirv GL_ARB_spirv_extensions GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_INTEL_shader_atomic_float_minmax GL_INTEL_shader_integer_functions2 GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation 

PTB-Info: Running on 'The X.Org Foundation' XServer, Vendor release 12101001.

**Comment by kleinerm** [comment] 2021-06-09 18:11
How did you get all these Octave versions for Ubuntu 20.04 LTS?

Haven't tested with Ubuntu 21.04 myself yet due to lack of time.

Wayland is unfortunately not really ready for Psychtoolbox, especially not the XWayland X-Server emulation used in your case. Maybe things got worse with the XWayland 1.21 server that seems to be in use on your machine, compared to older Ubuntu versions?

What happens with the ``help ConserveVRAMSettings``option ``kPsychDisableOpenMLScheduling`` ie. ``Screen('Preference','ConserveVRAM', 2^19);``?

I don't expect any reasonable timing or performance from this, probably wil end in sync failure, but maybe avoids the hard hang.

The only way to use PTB atm. is by switching back to the native XOrg session at the login prompt. We have an experimental PTB Wayland backend, but that is not part of the official distribution, and incomplete. And almost all current Wayland implementations are not good enough for neuroscience use yet.

Please consider buying a community membership to financially support future work to proper Wayland support.

**Comment by kleinerm** [comment] 2021-07-29 13:03
Confirmed with Ubuntu 21.04 + Ubuntu desktop Wayland, that the ``Screen('Preference','ConserveVRAM', 2^19);`` works around the problem, ofc. now causing sync failure often, and bad timing always. Switching to the XOrg session fixes all issues and we are good again.

Iow. Nothing new here under the sun... ...Closing.

**Closed by kleinerm** 2021-07-29 13:03 UTC
Labels: notourbug
