### ISSUE TITLE
Bogus mogl return values on R2015b

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#308] opened 2016-01-13 09:35 UTC
Code that works on <= R2015a or Octave fails on R2015b due to incompatibiities. In general many OpenGL functions which return/query data from the system will fail/return bogus results. The OpenGL calls themselves will work, but we have a breakdown in the mex file communicating those results back to Matlab

E.g. glGenBuffers will always return a 0 handle on 2015b, but 0 is not allowed as a handle when using glBufferData, hence the "invalid operation" error.

See forum message 20078 and 19857

**Comment by scarfelab** [comment] 2016-05-29 14:13
Any idea who this bug will be fixed. Is there anything I could help with to fix it?

**Comment by dcnieho** [comment] 2016-08-24 22:24
sorry, just see your reply now. I have tried to have a look but noticed that:
1. I have no idea what the actual problem is, so no idea how to manually fix it (so i can test what should be changed)
2. the code generators do not support windows. 

@kleinerm, do you have a hint in whats wrong in the generated code (C-code, or M-code?) that causes this problem? Perhaps we can take glGenBuffers as an example, if we know what to change there, we can do the leg work

**Comment by kleinerm** [comment] 2016-09-28 19:28
The problem is that Mathworks broke backwards compatibility with how they treat righthand side "input" arguments in R2015b for their mex api. You can no longer pass data back via preallocated (by M-Files) prhs[] mxArrays, as we do in moglcore. The data simply doesn't show up on the M-File side, apparently because they no longer pass pointers to the underlying interpreter data structures, but instead only to copies of the input arguments from the M-function. Probably part of their new execution engine which can be a bit faster for some types of apps. To be fair, the approach of doing so was never a recommended practice, but rather discouraged by them. However, it worked for more than 20 years since at least Matlab-5, so nobody ever expected them to break that. Nobody expects the spanish inquisition...

Anyway, this means a rewrite of our code generator to handle this, which may or may not be straightforward, depending on tiny details. One hard part being the avoidance of regressions. As i only have to deal with it about every 3 years, it usually takes me already half a day to just familiarize myself again how that codegen code works. I'd estimate anything between 1-2 days, 1-2 weeks or a full rewrite of the whole approach to do it properly. Or manual conversion of up to 148 affected functions atm.
Not a high priority at all, compared to other stuff, given that this can be easily worked around by choice of Octave or any slightly older Matlab version.

Are there other critical functions than glGenBuffers() which are needed by @dcnieho or @scarfelab ?
I'll have to do some maintenance on moglcore, so i'll port glGenBuffers manually, and maybe one or two more if i'm in a good mood.

**Comment by dcnieho** [comment] 2016-09-28 20:31
Thanks for looking into this and clarifying what is needed. I have no
functions i stumble over, using no more than display lists so far and not
frequently. @scarfelab, do you feel comfortable editing this wrapper code?
I found it somewhat impenetrable when i had a look. But Mario is clear
about what needs to be done. Sadly there are no good tests when it comes to
finding regressions. do we have any tests covering mogl at all? Perhaps
running your own code is a good one Peter? I can assist.

**Comment by scarfelab** [comment] 2016-09-29 08:40
Are there a list of functions that need modifying? That would help in working out which functions I use are effected. That, or I could just list all the OpenGL functions used after the glGenBuffers() call which is where the current code crashes. 

I'd be happy to have a look at this code. Are there any instructions and comments for how it works? However, my main worry is that Mario mentioned it would take him possibly up to 1-2 weeks, so for me, who is not familiar with the PTB source code, I imagine it would take much longer. 

Anyway, I would certainly be happy to look into whether it would be possible for me to fix. But I warn I no-longer have the ability to spend a large amount of time on this as term has started here and now as a lecturer my time easily gets soaked up with non-research matters (much to my dismay).

**Comment by kleinerm** [comment] 2016-09-29 12:44
If you go into the Psychtoolbox/PsychOpenGL/MOGL/wrap folder and execute
grep allocate gl*
that gives you potential 148 candidates. However, a
grep allocate gl* | grep Get | wc --lines
shows that 108 are glGet queries, which are not often needed in typical rendering code, more for advanced rendering techniques or computer vision/image processing/gpgpu algorithms. Most of the time one tries to avoid reading data back to the host computer in high-perf rendering, as these are cpu-gpu synchronization points which can massively reduce performance.

The lists will also contain false positives - functions only available in core OpenGL 3/4, which are automatically wrapped but not actually usable from a OpenGL1/2/3.0/3.1 compatible application.

grep allocate gl* | grep Gen
shows the 16 probably important/common ones. However, of these, i doubt anybody will use much more than glGenBuffers(), given that most users of PTB are probably beginners in OpenGL with rather basic needs for creating simple 2D/3D stimuli. If they needed complex VR'style environments or 3D scenes with research grade stimulus presentation control hey'd likely use our Horde3D engine support, and for regular VR/3D scenes where they don't need any precise control over timing/contrast/color/stimulus display/response collection they'd probably just use some regular game engine.

In fact you are the only person that ever complained about lack of support for this on R2015b+, so i assume apart from PTB's own moglmorpher() and moglFDF() functions, nobody else ever missed these functions. And for VBO based rendering one doesn't strictly need more than glGenBuffers.

Wrt. comments or how it works? No. "Use the source" is all there is, and a pretty sight or a simple path it is not, with a mixture of Unix shell scripting, regular expression parsing, and M-Code.

**Comment by dcnieho** [comment] 2016-09-29 22:55
Ok, i looked into this a bit, and the parser/generator code would probably have to be come more complicated to make this work. Perhaps implementing glGenBuffers by hand and calling it quits is the best idea. Quickest, and you'll probably never have to run the generator again anyway, as the supported bits of OpenGL don't change anymore. So why fix that?

**Comment by kleinerm** [comment] 2016-09-30 01:29
Not sure what you mean with "don't change anymore"? OpenGL is still evolving, new extensions to OpenGL 4 are developed all the time, so at some point we'll see a core OpenGL 4.6 version, and these extensions are accessible even from OpenGL 2.x and 3.0. mogl should be able to support at least the functions which are accessible from a scripting language eventually. Not all functions can be sensibly/easily used from Matlab or similar scripting languages, because they need C-style pointer access. The wrap directory contains many _glFunctions prefixed with _ that cannot be enabled automatically, or possibly at all in Matlab. But many functions can be used.

I hope to fix the code generator at some point, just not now, so porting 1 or a few functions manually will hopefully be a good enough short term fix.

**Comment by scarfelab** [comment] 2016-09-30 07:55
Ok. Looks like a temporary fix to a couple of functions looks like the best solution for now. I'm surprised I'm the only one who appears to use these functions. I guess Mario is right and the people tend to use PTB for simpler stimuli. 

Some colleagues and I will be releasing a library of laser scanned 3D objects for use in psychology experiments and our aim was to provide support via PTB code for rendering and manipulation of the meshes. So it would help with that in addition to my particular experiments. 

We got a lot of interest for this at VSS. 

I'll follow Mario's instructions so I can highlight the functions we use which are affected. 

Thanks for both of your help.

**Comment by dcnieho** [comment] 2016-09-30 18:06
Ah sorry, i misunderstood somehow that new extensions would be limited to
ogl4 contexts. Maybe then the "fancy features nobody uses, lets not fix
until requested" still works fine :)

**Comment by kleinerm** [comment] 2016-10-03 11:45
According to the user survey about 16% of labs are interested (or use?) the low level OpenGL interface. I assume most just do fine with immediate mode calls or all the other performance mechanisms which don't require VBO's, e.g., display lists, client vertex arrays etc. Only about 3.8% use a Matlab version of R2015b or later, according to our last stats from March 2016 -- the registration server is down, so we lack more recent data. So of those who may use VBO's and other "fancy" stuff, many are likely not affected due to use of Octave or older Matlab versions. Most of the labs i know here do not upgrade quickly to new Matlab versions, because they see little benefit, but risk of disruption of day to day work. I guess whatever was current when they first installed a new machine is what they stick to. I myself use 2012a and seldom something more modern, because hassle of upgrading and i mostly loathe the "new" GUI, apart from the fact i don't use Matlab very much at all - Octave is perfectly adequate for me and has faster startup times, lower resource consumption and no license server hassle.

Parallel installation of an earlier Matlab version is easily doable and not a big workaround if one is on a maintenance contract, or simply using Octave. So it's entirely possible you are the only affected person atm. Can you send some small self contained sample project with your new 3D stuff that would work OS independent? If there is more than 1 function i need to port, i'd like to do this in one go, and i wouldn't port more than a handful myself, so we better choose the right ones.

**Comment by scarfelab** [comment] 2016-10-04 08:38
Thanks Mario, I am out of the office for a few days but will send information once I am back later in the week.

**Comment by scarfelab** [comment] 2016-10-07 17:19
Back in town now. I will modify one of our experimental scripts to make a minimal example which does the same rendering but without all the experimental baggage. That will aid seeing whats relevant. Thanks. P

**Comment by scarfelab** [comment] 2016-10-16 13:19
Mario: I just emailed you a relatively minimal piece of code which shows the functions being used. The vast majority of the code can be ignored as it fails on line 280 and there is little code after that. Please let me know if there is any help I could provide.

**Comment by kleinerm** [comment] 2016-12-07 07:02
So this turned out to be not something clever and intentionally backwards incompatible in R2015b, but now looks like a stupid bug they made and never noticed. If one passes matrices with only 1 element (iow. scalar) then the interpreter screws up, and back-passing of data doesn't work anymore. If the matrix/vector/whatever has at least 2 elements then everything seems to work as before. The new hack is was now to modify all affected M-Function wrappers to always pass in at least a 2 element matrix or vector, even if only 1 element is expected as return, then after moglcore call, to strip away that extra element again. Less awful than rewriting tons of C code manually, only a dozen hours of mind-numbing work instead of hundreds of hours.

Anyway, demos which didn't work before like MorphDemo, FDFDemo, work again on R2015b as tested on Linux and OSX, and Peters reference code should also work. Of course there's some good potential of me having made some mistake after hours of dull work on this crap, introducing some new regressions in previously working code. Released in the beta from today, so closing...

**Closed by kleinerm** 2016-12-07 07:02 UTC
Labels: bug
