### ISSUE TITLE
Issue with GStreamer and PTB 3 with 64 Bit Matlab and 64 Bit Windows 8

### ISSUE THREAD

**Issue by vr90** [Psychtoolbox-3/Psychtoolbox-3#234] opened 2015-02-18 23:43 UTC
The Screen function doesn't work properly when SimpleMovieDemo is run. The startup screen says there is an issue with GStreamer but I have installed the latest update. Is the only solution to this to revert to 32 Matlab and a prior version of PTB, GStreamer? If so which ones - has there been any success with using different versions of PTB and GStreamer on a 64 Bit Matlab system? Thanks

**Comment by vr90** [comment] 2015-02-19 00:02
This the 2013b Version of Matlab btw...

**Comment by dcnieho** [comment] 2015-02-19 07:24
please provide information about the system (window, osx, etc?). Is ptb
completely up to date? What version of gstreamer have you installed? And
lastly, please copy the message you receive here

**Comment by vr90** [comment] 2015-02-19 14:47
Hi,

The system is windows 8 64bit. PTB is up to date(Version 3.0.12). The version of gstreamer is 1.4.5 64bit. Matlab is 2013b. When I run SimpleMovieDemo, I get the white screen with Psychtoolbox 3.0.12 is checking graphics card and then screen goes black and crashes -  I am running dual display. I get the message that Screen function isnt able to run because one of the gstreamer libraries may not be installed, etc even though I have installed all the libraries during gstreamer installation. I will post the exact message here soon as well.

Vineeth

**Comment by vr90** [comment] 2015-02-19 17:25
SimpleMovieDemo
PTB-INFO: Multi-display setup in explicit multi-display mode detected. Using the following mapping:
PTB-INFO: Screen 0 corresponds to the full Windows desktop area. Useful for stereo presentations in stereomode=4 ...
PTB-INFO: Screen 1 corresponds to the display area of the monitor with the Windows-internal name \\.\DISPLAY1 ...
PTB-INFO: Screen 2 corresponds to the display area of the monitor with the Windows-internal name \\.\DISPLAY2 ...
PTB-WARNING: Screens 1 and 2 do have non-equal width and height. This will probably cause wrong behaviour
PTB-WARNING: when trying to open a fullscreen window on Screen 0 that is supposed to fully cover displays 1 and 2.
PTB-WARNING: In that case, either change your screen settings to matching size and refresh rate in the display control
PTB-WARNING: panel and retry after a 'clear all', or manually specify a [rect] parameter for the window in the
PTB-WARNING: Screen('OpenWindow', 0, [color], [rect]); command to manually enforce creation of a proper onscreen window.



PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.12 - Build date: Nov  5 2014).
PTB-INFO: Support status on this operating system release: Windows version 6.2 partially supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Will disable DWM because a regular fullscreen onscreen window is opened -> We want best timing and performance.
PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAM', section 'kPsychUseBeampositionQueryWorkaround'.


PTB-INFO: OpenGL-Renderer is Intel :: Intel(R) HD Graphics 4400 :: 4.2.0 - Build 10.18.10.3308
PTB-INFO: VBL startline = 1200 , VBL Endline = 1200
PTB-INFO: Measured monitor refresh interval from beamposition = 16.677742 ms [59.960155 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.683265 ms [59.940304 Hz]. (50 valid samples taken, stddev=0.051733 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.949153 ms [59.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-WARNING: ============================================================================================================================
PTB-WARNING: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE ON AT LEAST ONE DISPLAY! ALL FLIP STIMULUS ONSET TIMESTAMPS WILL BE LIKELY WRONG!
PTB-WARNING: STIMULUS ONSET TIMING WILL BE UNRELIABLE AS WELL, AND GRAPHICS PERFORMANCE MAY BE SEVERELY REDUCED! STIMULUS IMAGES MAY NOT
PTB-WARNING: SHOW UP AT ALL! DO NOT USE THIS MODE FOR RUNNING REAL EXPERIMENT SESSIONS WITH ANY REQUIREMENTS FOR ACCURATE TIMING!
PTB-WARNING: ============================================================================================================================
PTB-INFO: Support for fast OffscreenWindows enabled.

------------------------------------------------------------------------
          Access violation detected at Thu Feb 19 12:09:27 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Default Encoding   : windows-1252
  MATLAB Architecture: win64
  MATLAB Root        : C:\Program Files\MATLAB\R2013b
  MATLAB Version     : 8.2.0.701 (R2013b)
  Operating System   : Microsoft Windows 8
  Processor ID       : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : Version 6.2 (Build 9200)

Fault Count: 1


Abnormal termination:
Access violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 00000000c1ea6050
  RCX = 00000000c1ea6050  RDX = 0000000108667050
  RSP = 00000000040356d0  RBP = 000000010869404c
  RSI = 000000006e99a519  RDI = 0000000108657000
 
   R8 = 0000000007511140   R9 = 0000000000000084
  R10 = 0000000000000001  R11 = 0000000000000008
  R12 = 0000000000000004  R13 = 000000006e99a540
  R14 = 000000006e99a522  R15 = 0000000000000000
 
  RIP = 000000010800d335  EFL = 00010246
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x000000010800d335 C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\libgstlibav.dll+00054069
[  1] 0x00000001080014a0 C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\libgstlibav.dll+00005280
[  2] 0x000000006e939905 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00301317 gst_pipeline_get_auto_flush_bus+00002101
[  3] 0x000000006e93b478 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00308344 gst_plugin_load_file+00000552
[  4] 0x000000006e946eeb C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00356075 gst_query_set_context+00000571
[  5] 0x000000006e948414 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00361492 gst_registry_remove_plugin+00002020
[  6] 0x000000006e948486 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00361606 gst_registry_remove_plugin+00002134
[  7] 0x000000006e949eb8 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00368312 gst_update_registry+00002808
[  8] 0x000000006e8f1b90 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00007056
[  9] 0x000000006f41b4e8      C:\gstreamer\1.0\x86_64\bin\libglib-2.0-0.dll+00242920 g_option_context_parse+00000856
[ 10] 0x000000006e8f24d1 C:\gstreamer\1.0\x86_64\bin\libgstreamer-1.0-0.dll+00009425 gst_init_check+00000193
[ 11] 0x00007ffe97ce51e3 C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00283107 mexFunction+00235507
[ 12] 0x00007ffe97cdd582 C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00251266 mexFunction+00203666
[ 13] 0x00007ffe97cdc042 C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00245826 mexFunction+00198226
[ 14] 0x00007ffe97d0addf C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00437727 mexFunction+00390127
[ 15] 0x00007ffe97cabdae C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00048558 mexFunction+00000958
[ 16] 0x000000006d76f741 C:\Program Files\MATLAB\R2013b\bin\win64\libmex.dll+00063297 mexRunMexFile+00000129
[ 17] 0x000000006d76e212 C:\Program Files\MATLAB\R2013b\bin\win64\libmex.dll+00057874 inSwapMexfileReader+00000226
[ 18] 0x000000006d76f2c4 C:\Program Files\MATLAB\R2013b\bin\win64\libmex.dll+00062148 _constructor_lm_mexmaci64+00001620
[ 19] 0x000000018000d612 C:\Program Files\MATLAB\R2013b\bin\win64\m_dispatcher.dll+00054802 Mfh_file::dispatch_fh+00000674
[ 20] 0x000000018000defa C:\Program Files\MATLAB\R2013b\bin\win64\m_dispatcher.dll+00057082 Mfunction_handle::dispatch+00000810
[ 21] 0x000000000515c634 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00312884 inFunctionHandleInterface::DestroyWorkspace+00135604
[ 22] 0x000000000516fa37 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00391735 inFunctionHandleInterface::DestroyWorkspace+00214455
[ 23] 0x000000000518dc4f C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00515151 inFunctionHandleInterface::DestroyWorkspace+00337871
[ 24] 0x0000000005176639 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00419385 inFunctionHandleInterface::DestroyWorkspace+00242105
[ 25] 0x000000000517feaf C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00458415 inFunctionHandleInterface::DestroyWorkspace+00281135
[ 26] 0x0000000005182e23 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00470563 inFunctionHandleInterface::DestroyWorkspace+00293283
[ 27] 0x000000000516b85f C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00374879 inFunctionHandleInterface::DestroyWorkspace+00197599
[ 28] 0x000000000516b7c8 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00374728 inFunctionHandleInterface::DestroyWorkspace+00197448
[ 29] 0x000000000518ebbd C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00519101 inFunctionHandleInterface::DestroyWorkspace+00341821
[ 30] 0x000000000518b5cc C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00505292 inFunctionHandleInterface::DestroyWorkspace+00328012
[ 31] 0x000000000516e529 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00386345 inFunctionHandleInterface::DestroyWorkspace+00209065
[ 32] 0x000000018000d612 C:\Program Files\MATLAB\R2013b\bin\win64\m_dispatcher.dll+00054802 Mfh_file::dispatch_fh+00000674
[ 33] 0x000000018000defa C:\Program Files\MATLAB\R2013b\bin\win64\m_dispatcher.dll+00057082 Mfunction_handle::dispatch+00000810
[ 34] 0x0000000005186a81 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00486017 inFunctionHandleInterface::DestroyWorkspace+00308737
[ 35] 0x0000000005210657 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+01050199 inEachVisibleName+00015383
[ 36] 0x00000000051846c2 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00476866 inFunctionHandleInterface::DestroyWorkspace+00299586
[ 37] 0x000000000516b85f C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00374879 inFunctionHandleInterface::DestroyWorkspace+00197599
[ 38] 0x000000000516b7c8 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00374728 inFunctionHandleInterface::DestroyWorkspace+00197448
[ 39] 0x000000000518ebbd C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00519101 inFunctionHandleInterface::DestroyWorkspace+00341821
[ 40] 0x000000000518b5cc C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00505292 inFunctionHandleInterface::DestroyWorkspace+00328012
[ 41] 0x000000000516e529 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+00386345 inFunctionHandleInterface::DestroyWorkspace+00209065
[ 42] 0x000000018000d612 C:\Program Files\MATLAB\R2013b\bin\win64\m_dispatcher.dll+00054802 Mfh_file::dispatch_fh+00000674
[ 43] 0x000000018000defa C:\Program Files\MATLAB\R2013b\bin\win64\m_dispatcher.dll+00057082 Mfunction_handle::dispatch+00000810
[ 44] 0x000000000522438e C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+01131406 inSetWorkSpaces+00001262
[ 45] 0x00000000052306f5 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+01181429 SetInterpreter+00000325
[ 46] 0x0000000005232cb5 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+01191093 inEvalCmd+00008789
[ 47] 0x0000000005232c82 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+01191042 inEvalCmd+00008738
[ 48] 0x0000000005232c47 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+01190983 inEvalCmd+00008679
[ 49] 0x000000000561ad0c C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+05287180 inMexPutVariable+00008364
[ 50] 0x000000000561b066 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+05288038 inMexPutVariable+00009222
[ 51] 0x000000000561b49e C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+05289118 inMexPutVariable+00010302
[ 52] 0x000000000561b7dc C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+05289948 inMexPutVariable+00011132
[ 53] 0x000000000552ff91 C:\Program Files\MATLAB\R2013b\bin\win64\m_interpreter.dll+04325265 inEvalCmdWithLocalReturn+00000065
[ 54] 0x000000006c71be9d C:\Program Files\MATLAB\R2013b\bin\win64\libmwbridge.dll+00048797 mnDebugPrompt+00000109
[ 55] 0x000000006c71cf7f C:\Program Files\MATLAB\R2013b\bin\win64\libmwbridge.dll+00053119 mnParser+00000735
[ 56] 0x000000006e4ff4b4   C:\Program Files\MATLAB\R2013b\bin\win64\mcr.dll+00193716 mcrInstance::mnParser_on_interpreter_thread+00000036
[ 57] 0x000000006e4e44b0   C:\Program Files\MATLAB\R2013b\bin\win64\mcr.dll+00083120 mcr::runtime::setInterpreterThreadToCurrent+00029472
[ 58] 0x000000006e4e4510   C:\Program Files\MATLAB\R2013b\bin\win64\mcr.dll+00083216 mcr::runtime::setInterpreterThreadToCurrent+00029568
[ 59] 0x000000006b01fa96   C:\Program Files\MATLAB\R2013b\bin\win64\uiw.dll+00391830 UIW_IsUserMessage+00000086
[ 60] 0x000000006b020175   C:\Program Files\MATLAB\R2013b\bin\win64\uiw.dll+00393589 UIW_SetGLIMUserMsg+00000117
[ 61] 0x000000006b0201f9   C:\Program Files\MATLAB\R2013b\bin\win64\uiw.dll+00393721 UIW_SetGLIMUserMsg+00000249
[ 62] 0x00007ffead5fc01a                     C:\WINDOWS\system32\USER32.dll+00573466 BroadcastSystemMessageExA+00000558
[ 63] 0x00007ffead572fa5                     C:\WINDOWS\system32\USER32.dll+00012197 GetLastInputInfo+00000089
[ 64] 0x00007ffead573016                     C:\WINDOWS\system32\USER32.dll+00012310 GetLastInputInfo+00000202
[ 65] 0x00007ffead782c44                      C:\WINDOWS\SYSTEM32\ntdll.dll+00601156 KiUserCallbackDispatcher+00000036
[ 66] 0x00007ffead57313a                     C:\WINDOWS\system32\USER32.dll+00012602 PeekMessageW+00000202
[ 67] 0x00007ffead5764f3                     C:\WINDOWS\system32\USER32.dll+00025843 GetMessageA+00000243
[ 68] 0x00007ffead57649f                     C:\WINDOWS\system32\USER32.dll+00025759 GetMessageA+00000159
[ 69] 0x000000006aff94db   C:\Program Files\MATLAB\R2013b\bin\win64\uiw.dll+00234715 UIW_SetCurrentDialog+00000731
[ 70] 0x000000006b021632   C:\Program Files\MATLAB\R2013b\bin\win64\uiw.dll+00398898 ws_FreeSystemFont+00000482
[ 71] 0x000000006f156600 C:\Program Files\MATLAB\R2013b\bin\win64\libmwse

**Comment by kleinerm** [comment] 2015-02-22 20:18
This has been handled on the forum. Nothing new, running "matlab.exe -nojvm" should help on 64-Bit Windows. Closing...

**Closed by kleinerm** 2015-02-22 20:18 UTC

**Comment by belopsky** [comment] 2015-06-04 19:37
@kleinerm  but what if Java functionality is required? Don't think his has been 'handled'

**Comment by kleinerm** [comment] 2015-06-04 22:41
You need to improve your search skills then. This question has been asked and answered probably more than half a dozen times, often under almost the same subject lines that the next person uses to ask the same question again. If you need Java - which most people don't need - you can use a movie encoded in a different format that doesn't require the libgstav plugin, as described on the forum. Or you find a Matlab/Java version that doesn't crash. Or you use an old PTB version under 32-Bit Matlab. Or you use Linux as operating system.

Over a week has been spent trying to debug this bug remotely, but the problem never happened on my test machine, and the affected users lacked the debugging skills and willingness to do multi-threaded debugging of complex C and Java code under MS Visual C++, something that would be very difficult even if the problem would happen on my own machine, given that Matlab is a proprietary application with no access to its source code. By now i don't even have a real Windows machine anymore for testing, only a badly working Virtual machine, so getting this properly fixed is very unlikely to happen anytime soon. As Windows is not a recommended OS for this kind of work in the first place, somebody would have to provide a seriously large amount of money to me for equipment costs and time before i would even consider trying another go at this.

**Comment by schragge** [comment] 2016-03-29 17:28
I've got the same problem on a fresh install of 64-bit Windows 10 with 64-bit Matlab 2016a. After I noticed Matlab reporting  Java 7 VM in the crash dump although Java 8 was installed, I installed Java 7 as well and that solved the problem.

**Comment by babaq** [comment] 2017-04-07 01:24
@schragge  could you provide some details about solving this issue on x64 win10 and matlab R2016a?

**Comment by schragge** [comment] 2017-04-07 07:46
@babaq IIRC, the problem showed up again when I upgraded to Matlab 2016b (even on Java 7 VM), but went away after upgrade to Matlab 2017a. Actually, I'm not sure what was the culprit, because I also upgraded to Gstreamer 1.10.4 and PTB 3.0.14 at the same time. But IIRC, it worked correctly even with Matlab 2016b if started with the -nojvm switch as answered by kleinerm above. See also [this answer](https://github.com/Psychtoolbox-3/Psychtoolbox-3/wiki/FAQ#how-to-resolve-gstreamer-problems) in the FAQ.

It's still using Java 7 VM, however. I've not tried it with Java 8. BTW, how to change the JVM used by Matlab is described [here](https://www.mathworks.com/matlabcentral/answers/130359-how-do-i-change-the-java-virtual-machine-jvm-that-matlab-is-using-on-windows?s_tid=answers_rc1-1_p1_Topic).

**Comment by zewushui** [comment] 2020-11-26 03:00
It may be caused by the mismatch between system variable name of 'Gstreamer' in your computer system and the name in PsychStartup.m in your PTB file. If this two names do not match, then ptb can not find the right path  in your system. So check it and the problem may be solved. I used win10 and both gstreamer and ptb are latest.
