### ISSUE TITLE
Windows: Text bounding box/positioning not as expected

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#254] opened 2015-07-22 13:53 UTC
hi Mario, all,

The context of the below is that I am developing a DrawFormattedText derivation that can interpret formatting codes in the string for bolding, italicizing, underlining and font, color and size changing.
When changing size in a line, we need to make sure all characters on the line are drawn with the same baseline.
So I looked into how text is positioned when yPositionIsBaseline==true and when yPositionIsBaseline==false. I thought the different should be a fixed vertical shift (constant for a given size, font and style). However, I found that on Windows 7 32 bit last PTB 3.0.11, as well as an up to date PTB on windows 8.1 64bit, text position _in_ the bounding box changes as yPositionIsBaseline is true or false. Is this right or a potential bug? There also may be an off by 1 bug in there (bounding box is one pixel too high), not sure about where a -1 in the C code comes from. Its all discussed further in the example script.

Note further that this seems to be font dependent. I get larger differences with Consolas than with Courier New.

Sample script here:
https://gist.github.com/dcnieho/7849b5d6b12ad43b765d
Screenshot of my output here:
https://www.dropbox.com/s/o2m1mnefb87sdrk/screenshot.png?dl=0

All the best,
Diederick

**Comment by kleinerm** [comment] 2015-07-29 17:32
I don't have a good answer to this one. Indeed a quick test with DrawFormattedTextDemo and DrawHighQualityUnicodeTextDemo and DrawMirroredTextDemo shows that bounding box calculation on Windows is much less accurate on Windows than on Linux and OSX. I'm happy i don't have to look at our Windows rendered text daily, the layout is quite ugly and looks "cheap" compared to the OSX and Linux results. On Linux, e.g., your sample script produces text and bounding boxes which look much better, essentially perfect, nowhere as your Windows screenshot.

1. These bounding boxes will never be fully accurate, as they are calculated from geometric info in the font definition files, using text renderer specific layout and hinting algorithms. Both the meta-info in the font files themselves and their interpretation by the used algorithm can and will be inaccurate to some degree. It's an accuracy vs. performance tradeoff. That's why you get results of different quality depending on the font/style/size used, and depending on OS. The only way to get a precise bbox is using something like our TextBounds command to draw text into offscreen, take a screenshot via GetImage, then find the true boundaries at pixel accuracy via simple image processing.

2. Ideally we'd use the same text render on all systems. On Linux and OSX we now use the Linux plugin renderer, based on fully open-source libraries. On Windows the problem is the usual dll dependency hell. Linux has the required libs installed by default, on OSX they come with their XQuartz Apple X-Server. On Windows they are not part of the OS or Matlab, so we'd have to bundle more dll's and make installation of PTB even more complicated. I'm not thrilled about doing that.

3. yPositionIsBaseline defines what the y coordinate means that you pass into 'DrawText'. Is it the top of the text bounding box, or the "baseline" on which the text string rests. The baseline is well defined, so whatever you try to do should probably only use the yPositionIsBasline=1 setting, if you want to mix text of different styles. The definition of "top" of bbox is difficult, because top-left of bbox is dependent on the specific text string, and where each character glyph of a font defines its top and how the hinting algorithm works. So it is confusing and unexpected, but completely correct that the text cursor position you set and that DrawText returns (x,y) is not actually the top-left corner of the expected bounding box. I've gone in circles multiple times trying to find bugs in our code and then realizing it isn't a bug but just something that i always forget. Given that each renderer and font does this a bit different it is pretty impossible to get this consistent across os'es without using exactly the same renderer and same set of font files.

4. Now that off-by-one bug you found is probably not caused by the code, that -1 is likely needed, although i can't remember why, i do remember tweaking there to avoid crashes or visual artifacts.

5. Could be that some of those DT_XXX flags one can pass to DrawTextW() would somehow help to align the Windows behaviour better with the LInux/OSX behaviour. There seem to be a couple of flags related to exact text positioning and bounding boxes. I don't have time or the nerves to play around with that stuff, especially not in my crappy Windows VM running on my crappy OSX, where starting Matlab already takes 5 Minutes and you can't work with that Windows VM for more than half an hour without getting the urge to smash things around you. So if you want to compile Screen yourself and play with this, go ahead, i don't have the nerves :).

The main problem around DrawFormattedText and your imho ambitious attempt to build a version that allows mixing different fonts/styles/sizes is that our text renderer isn't really built to handle more than single style/size/font text in a single line. Imho DrawFormattedText is already pushing the limit of what can be sanely done in Matlab script, with the limited and approximate bounding box info our renderer exposes.

To do this properly across os'es at good quality and performance we'd need a new text renderer inside the Screen mex file that is equipped to not only do text rendering but actual text layout. That's why 'DrawText' can use text rendering plugins, dynamically loaded as shared libraries from the file system. This is not yet implemented on Windows but would be relatively easy to extend. On Linux and now OSX we select one single rendering plugin for 'TextRenderer' type 1 or 2. One could allow loading of alternative plugins via 'TextRenderer' 3, 4, 5, ... Now text layout + rendering is computationally more expensive than just rendering. Our current plugin is optimized to do what it does almost as fast as one can do it in OpenGL. There's a second alternative plugin for use with OpenGL-ES which is even a bit faster, but only on Linux atm. If you wanted a really good text layout you'd need to implement an alternative rendering plugin which is optimized for high quality layout instead of speed. There's a reason applications like Word, Web browsers, regular apps  etc. are slower than our renderer for rendering text - layout quality for complex text is more important than getting text drawn at 60 or 120 fps update rate.

My favorite basis/building block candidate for having an open-source, cross-platform, high quality layout text renderer would probably be Pango (http://www.pango.org/). It is also available for Windows. But as usual Pango will in turn depend on various other libraries, so you get another set of dependencies to make it work. And as usual those dll's are usually not installed on Windows by default. But it wouldn't be impossible to build such alternative text renderer plugins for optional use on LInux/OSX/Windows.

So it's all a tradeoff between how much effort you want to put in, how much dll dependency hell or trouble in installation it would be worth for users, compared to the current situation. Most experiments probably don't need more than what we have now - Unicode for international text, high quality anti-aliasing, high speed for dynamic stimuli and dynamic rendered text, some ok layout.

**Comment by dcnieho** [comment] 2015-08-04 14:30
Hi Mario,

Thanks a lot for the extensive answer. Having something like Pango would be very cool. Think of the possibilities! Not that many would care though, i guess ;) It could be another optional component, just like gstreamer, If we wanted to go down that route. While it is something i would enjoy (love proper typesetting), implementing it is not something i can commit to now.

My drawformatted text version that does various styles indeed works by drawing text elements per specific style combination as that all the current interface can handle. Aligning was a little difficult, but it now all works, with different sizes and the like in the same line. Only underlines look horrible, as they change when the font/style/size changes. Ella has volunteered to do a bit of testing on OSX and Linux and then I'll present it to you for comments and possible inclusion.

Thanks also for the many and detailed comments for the bounding box issue at hand. Indeed, playing with the DT_ flags is the only option i have now to see if bounding boxes can improve. And indeed, GDI text rendering is quite a bit less than beautiful sadly, no matter what quality request and related Screen('Preferences') are set. Its sufficient though.

Thanks again, will make noise when i know more.

**Comment by kleinerm** [comment] 2016-01-25 15:07
Fixed in "Into Darkness" by use of the FTGL text renderer plugin.

Btw. seems that GStreamer bundles the Pango library, so in principle the dependency problem wouldn't exist if one wanted to implement an alternative Pango based text renderer plugin.

**Closed by kleinerm** 2016-01-25 15:07 UTC
Labels: enhancement

**Comment by dcnieho** [comment] 2016-01-25 19:52
Cool, thanks!

**Comment by denispelli** [comment] 2016-01-25 20:17
If we're adding a new routine, I would suggest dropping the yPositionIsBaseline argument and assuming it is always true. That is how typography is done. The option was introduced as a fix when the psychtoolbox shifted hands and I noticed the change too late to go back. Mario introduced the flag so as not to break old user code. But if we're starting something new, it's better to just assume yPositionIsBaseline==true and not offer any option.

**Comment by kleinerm** [comment] 2016-01-25 20:32
Unfortunately it's not new. All our renderers behave like that since many years now, the old and new ones. The only new thing here is that now MS-Windows uses the same renderer as Linux and OSX. I don't think we can ever get rid of that flag without breaking tons of usercode in probably dangerous ways, like moving a fixation cross out of the intended fixation position -- not a good idea to use a '+' or such for that in the first place, but many people seem to do it.
