### ISSUE TITLE
"The external text renderer plugin failed to render the text string for some reason!"

### ISSUE THREAD

**Issue by matanmazor** [Psychtoolbox-3/Psychtoolbox-3#579] opened 2019-08-20 14:29 UTC
Hi,
I'm running Psychtoolbox on Matlab2018b on a Windows machine. When trying to print text to the screen using either DrawText or DrawFormattedText I'm getting the same error message:

`Error in function TextBounds: 	Usage error
The external text renderer plugin failed to render the text string for some reason!`.

I tried to follow the instructions on #429 but I don't have an "AppData" folder or a "fontconfig" file. I did delete libfreetype.dll, but this didn't help.

Thanks!

**Comment by kleinerm** [comment] 2019-08-21 23:06
There must be a fontconfig folder somewhere. This error message means something went wrong in finding or loading a requested font. Deleting the fontconfig cache seems a good first step.

**Comment by matanmazor** [comment] 2019-08-22 10:12
Thanks! Turns out AppData was hidden - I now deleted the cache and restarted the computer, but I'm still getting the same error message:
`The external text renderer plugin failed to render the text string for some reason!`

**Comment by kleinerm** [comment] 2019-08-22 14:49
I assume our own text demos like DrawSomeText don't work either?

I assume you are on the very latest Psychtoolbox 3.0.16 (PsychtoolboxVersion tells you)? Maybe run UpdatePsychtoolbox again to make sure. Earlier versions of PTB are no longer supported. Current version requires GStreamer 1.16.0 MSVC edition to be installed, as our download instructions and system requirements sections on the website describe.

If it doesn't work, try this:

1. Open a Windows command shell, e.g., powershell.
2. cd into the 'C:\Program Files\MATLAB\R2018a\bin' folder.
3. Start Matlab like this: matlab.exe -batch DrawSomeText
4. Send me all the printed output into the shell command window. It might contain clues to what goes wrong.

In general the message means a requested font could not be found or loaded, for whatever reason. Could be dll problems, or corrupt fontconfig cache, or some permission problems wrt. fontconfig etc. or something damaged about the fonts on your computer.

**Comment by matanmazor** [comment] 2019-08-22 17:43
Many thanks for this kleinerm.
I just installed Psychtoolbox and followed the instructions carefully, including the GStreamer installation. I do notice however that the path to GStreamer is "C:\gstreamer\1.0\x86_64\bin", which seems to suggest the version is 1.0, not 1.16.0. The installation file I used though is "gstreamer-1.0-msvc-x86_64-1.16.0", so I guess that should be okay? I also now updated Psychtoolbox as you suggested, but the problem persists :-(

I'm attaching the printed output of the shell - it seems to just print the exact same text that is printed in Matlab?

Many thanks again,
-Matan
[PTBlog.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/3531287/PTBlog.txt)

**Comment by kleinerm** [comment] 2019-08-22 17:51
Your GStreamer and PTB is up to date. But the script aborted with sync failure, so it never made it to drawing any text. Maybe do matlab.exe -batch "PsychDebugWindowConfiguration; DrawSomeTextDemo" to disable the timing tests. Intel graphics chips are often highly problematic on Windows due to broken displays drivers.

**Comment by matanmazor** [comment] 2019-08-22 18:09
When skipping the tests I'm getting the same error message (line 43)

[PTBlog.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/3531385/PTBlog.txt)

**Comment by kleinerm** [comment] 2019-08-22 18:52
Hmm. The relevant error message is:

"libptbdrawtext_ftgl: FontConfig failed to find a matching font for family Courier New, size 50.000000 pts and style flags 3."

It means it can't find a font file on your system for the "Courier New" font at size 50. Shouldn't happen, as this is a quite basic font. I assume if you run other demos instead of DrawSomeTextDemo, e.g., DrawHighQualityUnicodeTextDemo, or DrawFormattedTextDemo, the error message will be similar, not finding that font?

It points to something being wrong with your systems installed fonts, or with the fontconfig database, but what specifically i don't know. I'd check that fontconfig cache file in that AppData folder to see if it got recreated after you deleted it - with a modification time/date that makes sense and a non-zero file size.

You can try adding a Screen('Preference','Verbosity', 7) in the above command before the call to DrawSomeTextDemo, to get even more verbose debug output. Maybe also add a setenv('FC_DEBUG','511'); -- This may create a huge log file - or no extra output at all.

**Comment by matanmazor** [comment] 2019-08-22 19:11
Okay, that's strange. I'm getting the same error message for DrawFormattedTextDemo. Fontconfig is still empty. I'm attaching the more verbose log. Thanks again, I really appreciate you help here!

[PTBlog.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/3531553/PTBlog.txt)

**Comment by kleinerm** [comment] 2019-08-22 19:55
Yes, that's the same failure although the search pattern looks correct. Unfortunately no debug output was created by libfontconfig itself, probably a limitation of Windows + Matlab.

What do you mean with "Fontconfig is still empty"?

**Comment by matanmazor** [comment] 2019-08-22 20:43
There's no file in fontconfig - it's completely empty.

**Comment by kleinerm** [comment] 2019-08-22 21:38
That's bad. There should be a cache subfolder with files in it. Otherwise fontconfig won't know which fonts you have and therefore won't find any.

C:\Users\mmazor\AppData\Local\fontconfig\cache\ should exist and have multi-megabyte files in it.

Not sure what could prevent that. Maybe some wrong permission settings for the folders?

**Comment by matanmazor** [comment] 2019-08-23 06:36
I've checked in different ways and it's definitely empty. Is this folder generated by Windows? Is there a way to recover the contents of this folder?

**Comment by kleinerm** [comment] 2019-08-23 15:31
No. The folder is created by the libfontconfig.dll library. libfontconfig is used to find a suitable (~ identical or closely matching in properties) font file on your system for the specified font family, size and style (Screen('Textfont'/'TextStyle'/'TextSize')). During first use of a Screen() text drawing function, or when certain trigger conditions are met, e.g., afaik installing new fonts on your machine or maybe operating system updates, libfontconfig scans your systems disc drive for font definition files in typical locations and builds a database of all font files and their (font-)properties. During normal text drawing libfontconfig uses that database to look up suitable fonts. This database is stored in that fontconfig/cache/ subfolders files. If the files are missing, incomplete or corrupt then fontconfig can't find suitable fonts and you get the error you got.

Normally if you delete all files in that fontconfig folder - or the whole fontconfig folder - fontconfig should just rebuild the whole database ie. recreate those folders and files. You'd note a script with text drawing functions pausing for a couple of seconds (or minutes worst case) depending on the number of fonts installed.

The weird thing - unique to your setup, never reported before by anybody - here is that apparently fontconfig can't or doesn't rebuild the font database, but also doesn't seem to report any error, although it should. So it's really unclear to me why this happens or where these database files are going. I wonder if one of those new "ransomware protection" features of Windows 10 somehow interferes, silently dropping all writes to that folder? I had many fights with the feature on my new development machine and in the end had to give up and disable the protection in my case :(.

Unfortunately low-level debug output of fontconfig does not seem to work on your machine either - the setenv('FC_DEBUG',...) settings apparently was ignored or the output went to nirvana. Normally that would help in debugging. Didn't work on my Windows-10 with Matlab either, only if i use Octave 5.1.0 instead. In general i recommend using Linux whenever possible, because many of these problems go away.

I rechecked on my system with FC_DEBUG logging with Octave and confirmed that that AppData/fontconfig/cache/ folder should get filled with cache files. Also that Fontconfig scans the C:\windows\fonts\ folder for font files. Maybe make sure that C:\windows\fonts\ is readable by you?

You didn't get any Windows notifications in that sidebar that some application (e.g., Matlab) was prevented from accessing the disc drive? Or does anything change if you go to Windows security settings and disable the ransomware protection thingy, then restart Matlab and run a text demo, then reenable it again?

Unfortunately if none of the above works, we are pretty much out of options, except maybe you trying the same steps with Octave-5.1.0 instead of Matlab, to see what debug output fontconfig produces in that case.

A different question is if you need good font rendering? For best performance, quality and consistent text rendering and positioning across operating systems, the plugin text renderer needs to be used. For emergencies we still have the old Windows-GDI text renderer as a fallback. Screen('Preference','TextRenderer', 0); at the top of your scripts would switch back to that text renderer. Text might be slightly misplaced in our demos, and inconsistent wrt. where it would go normally or an other operating systems. Some features might not work, speed will be slower, bugs could be present, especially with slightly non-standard fonts etc. But if all you want is to get some text on the screen then that might be a workable solution. We don't support that renderer though in case of problems or questions.

**Comment by matanmazor** [comment] 2019-08-23 17:25
Many thanks for this detailed answer!

I have access to C:/Windows/Fonts. 
I don't have the necessary permissions to disable Windows' ransomware protection - I'll have to ask our IT team to do it for me next week. 
Changing the text renderer setting to 0 worked, but for the long run I would prefer to know that behaviour is consistent across operating systems. AS a workaround, in the meantime I'm presenting my text as textures. I think I might just ask IT to install Matlab on my WSL and hope that everything works fine there. 

Again, many many thanks for this.
Best,
-Matan

**Comment by kleinerm** [comment] 2019-08-23 17:45
Ok, i think i'm out of ideas if you have read permission to C:/windows/fonts and write permission to that fontconfig folder. However, i think if ransomware protection is at fault, you should get some notifications in that side-bar thingy a la "blah protection prevented matlab from changing some files" or something like that.

If you mean Windows subsystem for Linux with WSL, that won't work. WSL is not good enough to true native Linux wrt. graphics and display to make PTB for Linux work meaningfully. If you installed an X-Server for Windows, you could get it to show visual stimuli, but timing, tearing, performance etc. would be beyond awful -- only good enough for entertainment purposes.

A dual-boot with Ubuntu 18.04.3 LTS of course should work, and given your Intel graphics under Windows 10 seems to be pretty broken -- as indicated by those failing sync tests -- it would also finally make your visual stimulation timing trustworthy on that machine.

Another thing you still can try is installing Octave 5.1 and run PTB with that, just to see if Matlab is involved in the problem -- very unlikely as i tested with R2019a, R2014b and i think R2014a, so R2018b should be fine. At least you'd get more meaningful debug output if you setenv('FC_DEBUG','1040'); before running a demo like DrawSomeText than in Matlab.

**Comment by matanmazor** [comment] 2019-08-23 18:07
Which side-bar thingy do you mean? I'm not seeing any message, but maybe I'm not looking at the right place?

In the interest of time, if you say it wouldn't work on WSL I might just stick with my workaround for now and simply avoid displaying text as text.

**Comment by matanmazor** [comment] 2019-08-23 18:11
I just noticed that when starting up Matlab the following lines appear:
`PsychStartup: Environment variable GSTREAMER_1_0_ROOT_X86_64 is undefined.
PsychStartup: Either GStreamer-1.16 MSVC is not installed at all, or if it is installed then something
PsychStartup: is botched. Trying various common locations for the GStreamer runtime to keep going.`
Could this be somehow related?

**Comment by kleinerm** [comment] 2019-08-23 18:16
Your previous log files don't show that problem, they say:
"PsychStartup: Adding path of installed GStreamer runtime to library path. [C:\gstreamer\1.0\x86_64\bin]"

Also, if that wouldn't work - it wouldn't find the right files, then the Screen() function would not work in the first place.
Trying with Octave 5.1 as explained on our website - it has a clickable download link - would be the most promising way of figuring out what went wrong. Also Octave is capable of running most Psychtoolbox scripts just fine, as long as they don't need special Matlab toolboxes or complex GUI or object oriented programming.

**Comment by matanmazor** [comment] 2019-08-23 18:25
When I run Matlab as administrator I get these additional lines on undefined GStreamer (which I don't get when running Matlab normally), but then *DrawSomeTextDemo* and *DrawFormattedText* work without a problem! 
Interestingly however the fontconfig folder is still empty after running these demos though.

**Comment by kleinerm** [comment] 2019-08-24 02:48
That means it's not a bug or problem related to PTB or Matlab or anything like that.
It is some kind of permission problem on your Windows machine, e.g., for the AppData folder or the fontconfig subfolder or some security mechanism going wrong. The data has to go somewhere, probably to a different location if you are the admin. Obviously this should work without running Matlab as admin.

Maybe try deleting the whole fontconfig folder inside the AppData folder, maybe also then logout and login again, or even reboot inbetween. I know that Windows has tons of these issues, if you Google for AppData and permission problems or similar terms. Sometimes they mysteriously appear or disappear after a Windows update or such. I'm just glad that i usually don't have to work under Windows :/

Essentially i consider this "Case closed", but if you find out why it happens, please report back for the benefit of others.

**Comment by matanmazor** [comment] 2019-08-24 14:14
Okay, thanks! I really appreciate your help on this.

I will add when running Matlab as admin I can't run the simplemoviedemo, suggesting that GStreamer is not recognized  (so potentially the reason that DrawText is working when running as admin is that GStreamer is not involved?).

cheers,
-Matan

**Comment by kleinerm** [comment] 2019-08-24 16:51
Maybe you are missing the H264 video decoder plugin? Did you install GStreamer as recommended with a "Full" or "Complete" installation, instead of "Minimal" or "custom"? If you don't do the complete install then certain codecs for patent encumbered formats will be missing, e.g., for H264, so SimpleMovieDemo would fail to play the movie.

However if GStreamers path would not be set right or inaccassible as admin, then the Screen() mex file itself would not work - Any visual demo would abort wit some "invalid mex file" error. If you even make it to any demo displaying anything or even text, then GStreamer path should be set and accessible correctly.

Drawtext requires GStreamer, as we get the required fontconfig.dll library from the GStreamer installation. Maybe post your output for a DrawSomeTextDemo run with Matlab as admin, or make sure there isn't any error/warning message about failure to load the DrawText plugin and falling back to the old text renderer?

The only way on Windows to get good debug output from fontconfig about problems is to run PTB with Octave in command line mode, otherwise the relevant debug output goes to nirvana.

**Comment by matanmazor** [comment] 2019-08-27 09:29
I now re-installed GStreamer with the complete, rather than the default installation, and now _SimpleMovieDemo_ works as administrator. So as administrator things seem to be working fine for me. When running _DrawSomeText_ as admin the only output to the Matlab console (apart from my usual synchronization check failures) is `Requested font: Courier New, got: Courier New
Requested font: Times, got: Times New Roman`

I will set up a reminder to run PTB with Octave to share the debug output next week when I have some time.

**Comment by kleinerm** [comment] 2019-08-27 12:50
Good. Have you tried deleting the whole fontconfig subfolder of the AppData folder and then running Matlab as normal user again? This must be some permission settings problem on your system or such, and sometimes just deleting stuff may help - fontconfig would recreate its folder on first run.

**Comment by matanmazor** [comment] 2019-08-28 11:59
I tried that now and it didn't seem to solve the problem.
I've also installed Octave on my machine but I want to be careful with installing psychtoolbox so that it doesn't affect my Matlab installation. Do you have any recommendation for how I should go about doing this? Specifically, if I run `DownloadPsychtoolbox('C:\toolbox')` from Octave, wouldn't it the files that I've already downloaded to this directory?

**Comment by dcnieho** [comment] 2019-08-28 13:12
in Octave, cd into the PsychToolbox directory and run SetupPsychtoolbox()

**Comment by kleinerm** [comment] 2019-08-28 16:49
Yes, what Diederick said. Octave and Matlab coexist peacefully wrt. Psychtoolbox.
After deleting the fontconfig folder and running Matlab as normal user again, did the .../AppData/fontconfig folder get recreated? Does it contain a cache/ subfolder with files?

Once you have Octave running, you can as first step type:

setenv('FC_DEBUG','1040'); and then run something like DrawSomeTextDemo. If that doesn't produce extra debug output, you can start Octave in the command line version and do the same - that definitely produces debug output.

**Comment by matanmazor** [comment] 2019-08-28 17:34
- fonctconfig got recreated, and it now contains a cache subfolder with two files in it (CACHEDIR.TAG, and some CACHE-7 file).
-_DrawSomeTextDemo_ runs on Octave, even not as admin, but takes a few seconds to start up.

**Comment by kleinerm** [comment] 2019-08-28 18:08
This is how it should work. Only the first time you run a text demo it should take a few seconds to start up, as the first use of text drawing will cause fontconfig to scan the systems font file folder and build those database files (CACHE-7...), then on future runs just use the info stored in those cache files.

What if you run Matlab as normal user again? Iff Octave as normal user can access all needed font folders (read-only) and write to the fontconfig/cache/ directory, i can't think of a regular directory access permission problem that would prevent Matlab from doing the same.

**Comment by matanmazor** [comment] 2019-08-28 19:40
Okay cool! 
DrawText is still not working with Matlab as a normal user though. Pretty strange!

**Comment by kleinerm** [comment] 2019-08-28 19:49
Ok, no idea anymore. Obviously you can't use the better debug output on Octave to find out what's going wrong if nothing is going wrong on Octave :/ - and we don't get meaningful log output with Matlab.

I assume no new CACHE-7 files showed up in the fontconfig/cache folder? I have one such file for Octave, one for Matlab.

Maybe check with a new user account if it works there? -> Something wrong with your account.
Or check the "ransomware protection" section in the security center to see if anything hints at Matlab being blocked from doing its thing by that mechanism. Can't help you with this, i've been thoroughly defeated by that thing - my solution was to disable it to get work done :(

**Comment by falkoin** [comment] 2019-11-07 13:57
I just solved this problem on a colleagues Windows machine.

It's probably not the most elegant method but should count as a work around.

MATLAB Version was 2019b and the the current PTB Version 3.0.16. We installed PTB Version 3.0.14 and uninstalled GStreamer. After that scripts displaying text works.
Not the most elegant method, but if you need a "quick" fix it might solve your troubles.

**Comment by kleinerm** [comment] 2019-11-07 15:01
That solution makes no sense. If the external text renderer can't be loaded, it will fall back to the old Windows GDI renderer, the same renderer that was the only/or default option in very old PTB versions. Your workaround essentially does nothing but prevent printing a warning message, while at the same time removing lots of improvements and introducing many bugs fixed since 3.0.14.

**Comment by falkoin** [comment] 2019-11-07 15:14
@kleinerm I mostly agree with your statement, but in my case the code for the experiment is written on a different machine than it will be ran on in the future (where the problem hopefully will not be present).
So if I have to choose between a maybe infinite search for the problem or just using a "hacky" fix, I choose the latter.

**Comment by kleinerm** [comment] 2019-11-07 15:39
Yes, but even if it solved your specific problem, that's not what i want to
encourage anybody else to do.

The result of your downgrade is expected to be 100% identical to you not
downgrading and leaving things as they are, the only difference being that
you avoid seeing one warning message. You silenced a warning message, but
the net result will be the same - you use the old unsupported GDI text
renderer with known limitations.

If somebody is bothered by the warning message, a more simple solution to
silencing the message is to simply explicitly switch to the old unsupported
GDI text renderer via: Screen('Preference', 'TextRenderer', 0); as
described in the troubleshooting guide for such problems (help
DrawTextPlugin").

If you experienced anything different, it could be interesting to know.

**Comment by falkoin** [comment] 2019-11-07 15:57
Now I am confused. In your reply you mention the problem being a warning. In my case the program crashed if any DrawText function was used. 

The full errormessage was:

`Error in function TextBounds: 	Usage error`
`The external text renderer plugin failed to render the text string for some reason!`
`Error using Screen`
`Usage:`

`[normBoundsRect, offsetBoundsRect, textHeight, xAdvance] = Screen('TextBounds', windowPtr, text [,x] [,y] [,yPositionIsBaseline] [,swapTextDirection]);`

`Error in DrawFormattedText (line 295)`
 `  theight = RectHeight(Screen('TextBounds', win, tstring));`

Reading this thread I assumed I had the same problem as @matanmazor, now I am not sure anymore. I also deleted the fontcache with no success. The problem began when a new MATLAB and PTB Version was installed on the machine (Win 10).

**Comment by kleinerm** [comment] 2019-11-07 16:01
Ok, that's a different error message that i thought it is - only skimmed
the title of the issue. But in that case the much better workaround is
still to switch to the old GDI text renderer, and the more easy and good
solution to do it is Screen('Preference', 'TextRenderer', 0); -- you only
"downgrade" the failing bit, not everything else as well.

**Comment by falkoin** [comment] 2019-11-08 11:10
Ok, I didn't know about the TextRenderer option. I totally agree that this is a much better solution.
I think your comment will help a lot of people, since I wasn't able to find a solution by googling before.
Thank you for your support!

**Comment by BHoring** [comment] 2020-08-19 09:18
Hello,

I seem to be having exactly the same issue as the OP and can't figure it out. Before I start describing: 

- PTB worked for me before on exactly the same setup (Win10, MATLAB2020a, etc.), when I used Screen('FillRect',...), Screen('DrawText',...) etc.
- One thing I can recall that changed was that initially, I accidentally installed GStreamer on an external HD (E:, for some reason, GStreamer installs by default on the highest drive number, and I didn't catch it in time) - I then uninstalled it and installed it again on the "proper" drive D:
- GStreamer has a proper entry in the windows PATH though, and MATLAB deceptively tells me at startup that
`PsychStartup: Adding path of installed GStreamer runtime to library path. [D:\gstreamer\1.0\x86_64\bin]`
- Another thing that may or may not be of interest: I had errors running a LiveScript recently because I accidentally left an PHP/Apache server running, and now at startup I sometimes get the 

```
Warning: Name is nonexistent or not a directory:
C:\Users\horing\AppData\Local\Temp\Editor_vxdxq 
```

Now, when I try to run DrawSomeTextDemo, the breakpoint seems to be
```
Error in function DrawText: 	Usage error
The external text renderer plugin failed to render the text string for some reason!
```
as in the OP (see attached [PTBLog.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/5095228/PTBLog.txt) for details).

- I have checked C:\Users\horing\AppData\Local\fontconfig\cache\ , and while there were files in it (presumably from the successful runs), they are not regenerated when I delete them and run PTB now (the dll is properly accessed though).
- I do have writing permissions in Windows/Fonts
- With Screen('Preference','TextRenderer', 0), it works "fine" but I'm not sure it will work for all our stimuli

[PTBLog.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/5095228/PTBLog.txt) 

p.s.: I hope this doesn't count as threat necromancy, but since it's the only one I found with this exact issue, I hope it'll pass.

**Comment by kleinerm** [comment] 2020-08-21 05:24
Don't know. The error message essentially means fontconfig could not find a suitable font, which means something is wrong with the fontconfig cache. So either it somehow can't rebuild the cache, or it can't find any font files to put into the cache.

GStreamers  C:\gstreamer\1.0\x86_64\etc\fonts\fonts.conf file on my machine suggests that caches are stored in the "Local Application Data" special folders fontconfig/cache subfolder, which would be normally C:\Users\horing\AppData\Local\fontconfig\cache\

The config file suggests that fonts should be searched inside the "Windows Directory" subfolder fonts, ie. in C:\Windows\fonts\

So maybe check if those locations have proper access permissions so that fontconfig can read (fonts) or write (cache) them?
Maybe also check if the paths above are really the proper ones for the "Windows Directory" special folder and "Local Application Data" special folder? There's this freeware app that allows to list all special folders on your machine:

http://www.nirsoft.net/utils/special_folders_view.html

**Comment by BHoring** [comment] 2020-08-26 07:44
Thank you for the pointers! Unfortunately though, no progress. Checked my fonts.conf file and the special folders, all are standard settings and the same as a working version on a different computer. Will try to use different MATLAB and PTB versions next.

I'm most confused about why it would work, and then stop working after gstreamer reinstallation (reverting to the initial status quo does nothing either)...

**Comment by kleinerm** [comment] 2020-08-27 13:34
I wonder if your system maybe has multiple copies of libfontconfig installed, and Matlab uses a different one than the one from GStreamer - with a different fonts.conf file or cache locations? Or some kind of permission problems prevent access?

There's Procmon for Windows, which you could try to log all file accesses of Matlab:

https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

That might give more clues.

**Comment by antigosa** [comment] 2020-10-15 12:32
Hi, 

I wonder whether this issue has been solved. I am having the same problem. I am seeing this error: 

![image](https://user-images.githubusercontent.com/9249735/96123298-89162c80-0eea-11eb-83e8-0f7a3c138dd7.png)

Not sure what happened. I have updated to the last version of Psychtoolbox and got this problem. I then came back to the version 3.0.14, but still experiencing the same issue. 

I have installed the Gstreamer as described in the Installation page. 

I have also installed Procmon for Windows, but not sure how to use it. Do you have any suggestions?

Thanks

**Comment by BHoring** [comment] 2020-10-16 06:06
Apologies for not responding to the procmon suggestion! FWIW, I did not mean any disrespect (nor to "ghost" anyone), but to the contrary, I felt like I was laboring on an issue that was leeching resources from both you and me. Since I could revert to working versions on other machines, I decided that I had invested enough time.

All your efforts are much appreciated in fact.

To the issue itself, I have used procmon in exactly the way described, with little avail as to what is actually going wrong. If you believe that _you_ might have any benefit from it, I'd be happy to provide you with some log files.

**Comment by antigosa** [comment] 2020-10-16 15:40
@kleinerm Sorry about it, I imagine it can be quite frustrating, but I can guarantee you that your time is not wasted and people really appreciate what you do, as you can see in BHoring comment. Thanks a lot for all your help, just know that without it, everyone would be just stuck!

Anyhow, thanks a lot for the guide on how to use Procmon, will do that when I see my computer. For now, I simply used the Screen('Preference', 'TextRenderer', 0) and it obviously worked.  Oh, and also the psychtoolbox text Demos do not work. 

The only thing that I realized is that Windows did update the night before, I don't know if it is related. 

Will let you know more when I have to more info

Cheers

**Comment by antigosa** [comment] 2020-10-18 16:03
Hi,

I managed to use Procmon, really useful tool, thanks for the guidelines. I have run **DrawFormattedTextDemo.m**.

I am not sure how to read this, should I just post the output here? It quite long. Or should I just post the resulting .PML file?

I can see that there are some issues with the fonts, I think. There are various "INVALID DEVICE REQUEST" for Gstreamer (e.g. D:\gstreamer\1.0\mingw_x86_64\etc\fonts\conf.d\40-nonlatin.conf), and Psychtoolbox (e.g. D:\Programs\toolbox\Psychtoolbox\Contents.m) when _operation_ is **FileSystemControl**. But also "NO MORE FILES" when _operation_ is **QueryDirectory**.

I can also see many NAME NOT FOUND (e.g. C:\Program Files\MATLAB\R2017a\bin\win64\libfontconfig-1.dll) when _operation_ is **CreateFile**. 

Does this help you in any way? Can you suggest to me which section of the results should I focus on?

Thanks
Raffaele

**Comment by kleinerm** [comment] 2020-11-19 18:48
So mingw_x86_64 in your GStreamer path tells me you installed the wrong GStreamer, not the msvc variant.

While my own machines worked just fine with the latest GStreamer 1.18 MSVC variant and the latest PTB 3.0.17, the one of my girlfriend failed with R2019b. At the same time an Octave 5.2 worked fine on the same machine. The solution for fixing Matlab was to delete the fontconfig cache. Then it got regenerated and eveything works again.

So what you should try is:

1. Update to the latest GStreamer 1.18 MSVC variant, as described in our "help GStreamer" and on our Website.
2. UpdatePsychtoolbox to the latest PTB 3.0.17 BETA. This would during the update try to update the fontconfig caches.
3. If 2 fails, delete the old fontconfig caches inside (assuming your user name is antigosa), e.g.,
C:\Users\antigosa\AppData\Local\fontconfig\cache\
4. Retry UpdatePsychtoolbox.

Other than that, you could use procmon again and add Filter rules in Filter->Filter. Rules like

1. "Process Name" "contains" "MATLAB"
2. "Path" "contains" "font"
3. "Path" "contains" "Font"
4. Maybe: "Operation" "contains" "QueryDirectory"

And start event capture, then run DrawSomeTextDemo, then stop capture. Then save and post the trace file somewhere i can read it. Adding step 4 would restrict the output to QueryDirectory calls, which give an idea of where fontconfig searches for fonts and font caches:

You should see a "Path" line of 

QueryDirectory should have a line 

C:\Users\antigosa\AppData\Local\fontconfig\cache with SUCCESS status, if it finds the cache directory.

If no supposedly valid and up to date cache is found (something in that folder that is like random numbers and letters followed by "-x86_64.cache-7", then a rescan of the "C:\Windows\Fonts\*" should happen, ie. a QueryDirectory operation with that folder, followed by many QueryDirectory lines that report lots of filenames of files inside C:\Windows\Fonts\

I verified with the latest 1.18 GStreamer versions that all config files are correct to trigger a scan of the C:\Windows\Fonts\ folder for new font files.

Maybe deleting the whole C:\Users\antigosa\AppData\Local\fontconfig directory might be also something to try if something is fishy with the access permissions on that directory.

So my results are so far that i don't know why Windows-10 screws up on some machines and not (most) others, but that it could always be resolved on my side by deleting the old fontconfig cache files or directories. Your turn again...

Oh, and if both of you @antigosa and @BHoring appreciate my work, since a few days there is a way to express that in cash. We do sell "community memberships with priority support" now, so labs can participate in the funding of PTB's upkeep, development and user support like this. The hope is that each lab buys such a membership once per year, for a rather modest fee which should be affordable at least for most labs. See:

http://psychtoolbox.org/prioritysupport.html

and

http://psychtoolbox.org/contribute
for background info.

In the future, dealing with issues that only affect a very small fraction of users, like this one, will not be possible anymore without such community memberships. General PTB maintenance/development and paid work takes precedence.

Thanks,
-mario

**Comment by antigosa** [comment] 2020-12-01 17:01
Hi,

thanks for your reply!

I have tried the first four steps, but that did not solve the problem, I am
still experiencing the same error.

[image: image.png]

I will try the other four as soon as possible, thanks a lot for the
explanation, and will let you know (it might take a while...).

Cheers
Raffaele


Il giorno gio 19 nov 2020 alle ore 18:48 kleinerm <notifications@github.com>
ha scritto:

**Comment by datalowe** [comment] 2021-02-19 10:45
For what it's worth, I got the same error message issue with `Screen('DrawText', ...)` on a Mac (Big Sur, 11.2.1), using Matlab (R2020b) with the latest PsychToolBox (3.0.17) and a 'full' install of GStreamer (using the '1.18.3 runtime installer'). It happened with the 'DrawSomeTextDemo', too. I'm not sure where the font cache that GStreamer/PTB attempts to use is located on Mac. I tried updating the read/write/execute permissions on any seemingly relevant gstreamer- and font-related folders I could find with 'sudo chmod -R 777' just to see if that would make any difference, but it didn't.

Since GStreamer hasn't released a version for Big Sur yet, it's possible that there's some compatibility issue there, or that Apple's increasingly aggressive 'privacy/security' permissions are blocking GStreamer from doing what it should, without asking me as a user whether permissions should be updated (I've been having this issue with a few other apps).

Since the scripts run fine on the computer that will actually be used with participants, while my computer will only be used for development, in the end I added `Screen('Preference','TextRenderer', 0)` as suggested by @kleinerm, and now it works as expected. Thanks for the quick n' dirty fix.

**Comment by kleinerm** [comment] 2021-02-23 18:03
Wrt. the trainwrecks, the cache is in ~/.cache/fontconfig/ iirc. Apples security theater is moving to the point where it makes the machines unusable for serious work. PTB's setup routine, running after each Download/Update/SetupPsychtoolbox, will install a new config file under ~/.fonts.conf via ...
``copyfile([PsychtoolboxRoot 'PsychBasic/macOS_fontconfig.fonts.conf'], [PsychHomeDir '.fonts.conf']);``
... to tell GStreamer libfontconfig where to find the fonts on a macOS system, then trigger a fontconfig cache update.

Ofc. macOS 11 is not yet officially supported or tested in any way by us. Given the serious bugs, i deemed it too risky to install it on my only OSX test machine -- there's real danger of hardware damage, apparently Apple thinks that only a computer one can't turn on anymore is a secure computer. A logical conclusion of all the other security theater.

**Comment by RomainPastureau** [comment] 2022-01-26 15:34
Hello, 
This being the most complete online topic on this specific issue, I'll put my quick answer here. 

I struggled with this problem all day because I couldn't find a folder under C:/Users/user_name/AppData/Local named fontconfig. It took me some time to realize that this folder was actually under C;/Users/user_name/.cache ; deleting the fontconfig folder in this latter path allowed me to finally be able to run my experiment (after one long minute processing all of the fonts installed on my computer). This process even created a new fontconfig folder under C:/Users/user_name/AppData/Local - I guess the two were conflicting for some reason. 

Maybe an ulterior version could fix this? Waiting for that, this workaround saved my day!

**Comment by mirh** [comment] 2022-10-19 15:05
> Ok, i think i'm out of ideas if you have read permission to C:/windows/fonts and write permission to that fontconfig folder. 

I don't know the specifics of ransomware protection, but its security could be totally separate from the usual "disk ACLs". 
It may very well be that while the user can do whatever they want from the Windows Explorer file manager with their own folders, normal programs (or if not any those not conforming to some new API) are denied access.

**Closed** 2023-09-22 18:03 UTC
Labels: notourbug

**Comment by kleinerm** [comment] 2023-09-22 18:05
Instructions wrt. this have been updated quite a while ago, and the next PTB beta will contain more fixes wrt. Windows, so close this for now and see if it reappears or not.

**Comment by mirh** [comment] 2023-09-23 11:25
It's nice that we could finally move on from old gstreamer/fontconfig. 
Though `download.markdown` is still hardcoding the link for the installer of version 1.20.5, instead of the official [download page](https://gstreamer.freedesktop.org/download/#windows) or the root of their [server](https://gstreamer.freedesktop.org/data/pkg/windows/?O=D).

**Comment by kleinerm** [comment] 2023-09-23 14:28
The PTB with the updated requirements is not yet released, so the instructions on the web page are mostly correct for the current release. The installer link is intentional, pointing to a somewhat tested release, giving Windows users a chance to get the "right" download from the start, instead of getting lost in complex instructions referring to many different variants on the official download page. Locking this thread. If people find new issues post-release, they can report them, and hopefully with proper paid support tokens attached.
