### ISSUE TITLE
lab2xyz (MATLAB internal) and LabToXYZ (PTB) produce different outputs

### ISSUE THREAD

**Issue by da5nsy** [Psychtoolbox-3/Psychtoolbox-3#735] opened 2021-09-23 19:11 UTC
**Describe the bug**
The internal MATLAB function for converting from CIELAB to XYZ produces different results to the PTB version of the same function (even when using the internal data for illuminant)

**To Reproduce**
```
% generate random LAB values for testing
rng(42) 
sz = [1,1000];
LAB = [rand(sz)*100;rand(sz)*40;rand(sz)*40]';

% convert using both MATLAB's inbuilt function and then the PTB function
XYZ_inbuilt = lab2xyz(LAB,'WhitePoint','d65');
XYZ_PTB = LabToXYZ(LAB',whitepoint('d65')');

% compare results
XYZ_PTBt = XYZ_PTB'; %transpose for comparison
any(XYZ_inbuilt - XYZ_PTBt,'all');

>> ans = 1
```

**Expected behavior**
```
>> ans = 0
```
(which would indicate complete equality)

**Desktop (please complete the following information):**
 - OS: Windows 21H1
 - Runtime: MATLAB 2019a
 - Version: 3.0.17 - Flavor: beta - Corresponds to SVN Revision 12153

**Comment by DavidBrainard** [comment] 2021-09-23 22:38
Doing an exact comparison is a bit brittle for a comparison, when there may be differences in the exact sequence of numerical calculations or the routines called to implement them.  The two methods agree to better than about.1 part in 10^6.  I don't think this is enough of a difference to be of concern. The version provided below illustrates the fractional difference numerical comparison, done in a way that avoids dividing by very small numbers when computing the fractional difference.  I often code numerical checks in this way, as I have found that two differently coded methods that should give the same answer often do not match perfectly (also true when comparing across results obtained on different hardware or across Matlab versions).  The code below also produces a scatter plot that the agreement is very good on the scale of the data.

DB

*******
% generate random LAB values for testing
rng(42) 
sz = [1,1000];
LAB = [rand(sz)*100;rand(sz)*40;rand(sz)*40]';

% convert using both MATLAB's inbuilt function and then the PTB function
XYZ_inbuilt = lab2xyz(LAB,'WhitePoint','d65');
XYZ_PTB = LabToXYZ(LAB',whitepoint('d65')');

% compare results in a manner that allows for small numerical differences
XYZ_PTBt = XYZ_PTB'; %transpose for comparison
maxDeviation = max(abs(XYZ_inbuilt(:) - XYZ_PTBt(:)));
fractionalDeviation = maxDeviation/mean(abs(XYZ_PTBt(:)));
if (fractionalDeviation > 1e-6)
    fprintf('Discepancy big enough to think about');
else
    fprintf('The two methods agree to better than about 1 part in 10^6\n');
end

% plot one against the other to give a visual sense
figure; clf; hold on
plot(XYZ_inbuilt(:),XYZ_PTBt(:),'ro','MarkerFaceColor','r','MarkerSize',10);
axis('square'); xlim([-0.2 1.2]); ylim([-0.2 1.2]);
plot([-0.2 1.2],[-0.2 1.2],'k');
xlabel('Built-in XYZ from LAB');
ylabel('PTB XYZ from LAB');

**Comment by DavidBrainard** [comment] 2021-09-24 15:31
Closing to be tidy.  Feel free to reopen if I've missed something.

**Comment by da5nsy** [comment] 2021-09-24 17:46
Thanks @DavidBrainard - very sensible. Thank you for the code example.

I came across this issue because I'm writing a `LuvTosRGB` script and my starting point was comparing the inbuilt `lab2rgb` with a PTB alternative (`LabToXYZ` -> `XYZToSRGBPrimary` -> `SRGBGammaCorrect`). I noticed that the output sRGB values between the two pipelines would differ in about 3% of cases. See, for eg:

```
rng(42)
sz = [1,1000];
LAB = [rand(sz)*100;rand(sz)*40;rand(sz)*40]';

%% inbuilt

sRGB_inbuilt = lab2rgb(LAB,'WhitePoint','d65','OutputType','uint8');

%% PTB

XYZ_PTB = LabToXYZ(LAB',whitepoint('d65')');
sRGBlin = XYZToSRGBPrimary(XYZ_PTB);
sRGB_PTB = uint8(SRGBGammaCorrect(sRGBlin,0)');

%% compare

comparison = double(sRGB_inbuilt(~all(sRGB_inbuilt == sRGB_PTB,2),:)) - double(sRGB_PTB(~all(sRGB_inbuilt == sRGB_PTB,2),:));
```

When the R and G values differ, they are higher in sRGB_PTB by a value of 1, and when the B values differ they are lower in sRGB_PTB by a value of 1.

These differences are small enough and infrequent enough to not concern me greatly, but they do make me curious (especially because they are not normally distributed but seem to affect each channel differently). When I saw that there were differences at the XYZ stage I assumed that this would be the cause, but you make a good point that these differences are indeed very small. Perhaps it is just the compounding of such small errors at each stage that results in the different sRGB values?

**Comment by DavidBrainard** [comment] 2021-09-24 18:20
My intuition is that the differences in XYZ are too small to be the cause of the sRGB differences, although I can't rule it out completely just by thinking.  Sounds more like a difference in the quantization that occurs in the gamma correction step of the conversion from XYZ to sRGB, or a difference in the conversion to the continuous pre-gamma corrected sRGB values.  I vaguely recall that there are some subtleties in the sRGB standard that aren't stated the same way in all sources.  I think I worked from what I regarded as the authoritative standard when I wrote the PTB routines, but it is foggy in my memory.  Could also be that the standard was revised in some way since I wrote those.  I will try to find some time soon to take a look.  If the built-in routines allow you to separate the steps in the computation, you could start with exactly the same XYZ values and probe the agreement in the various steps of the sRGB conversion.

**Comment by DavidBrainard** [comment] 2021-09-25 13:02
I did a little looking around on this.  The comments in the PTB routines indicate differences between the preliminary and final standard, and you can find discussions like this on the web: https://stackoverflow.com/questions/66360637/which-matrix-is-correct-to-map-xyz-to-linear-rgb-for-srgb

I think the PTB routines implement the numbers provided in the sRGB standard from the IEC, while the Matlab routines implement a version of sRGB that you can find in other places on the web and which some argue is preferable (see link above). The differences involve when you round various constants required to do the calculations, and there is a way to argue that the standard itself is ambiguous enough that both versions are consistent with it.  I don't think the Matlab routines existed at the time I wrote the PTB version. 

If you look at the talk section of the Wikipedia sRGB page and search on "Brainard" you will find some discussion from 2010 that involves me on this general issue.  At that time, I am pretty sure I persuaded the Wikipedia community that the definition on the Wikipedia should match the actual standard, but it looks like it has since changed.  I also assert in that discussion that I had a copy of the standard, and I'm sure I wouldn't have written that unless it was true.  I vaguely recall buying it so that I could be authoritative in what was in the PTB routines.  I will look around for it next time I am on campus.

Probably the right thing to do here is to improve the comments in the PTB routines (some of the links in them are broken) and possibly provide an option to compute in a way that matches the Matlab version (or to call the Matlab version.). I'll think about that more once I've tracked down my copy of the standard (or failed to do so.) It's possible that looking at it now will lead to a different conclusion about what the most accurate implementation is than I drew in 2010.

**Comment by da5nsy** [comment] 2021-10-01 19:17
Thanks for your enthusiasm @DavidBrainard! 

> If the built-in routines allow you to separate the steps in the computation, you could start with exactly the same XYZ values and probe the agreement in the various steps of the sRGB conversion.

I haven't dug too deeply to see whether the functions I've used here (`lab2xyz`, `xyz2rgb(XYZ','ColorSpace','linear-rgb')`, `lin2rgb`) are exactly what the comprises `lab2rgb`, but it's probably not an unreasonable start to think that they might.

Output figures at the bottom.

Summary: 
- A few points different (but only very slightly different) at the **LAB -> XYZ** stage
- Everything slightly different, with a clear (but not perfect) trend, at the **XYZ -> linear sRGB** stage  
- Nothing different at the **linear sRGB -> sRGB** stage
- I used the Vrhel surfaces, I've got some code in the works that uses some wackier values, and looks like it might unearth some other issues - will share when I can.


```
clear, clc, close all

%%

load spd_D65
load sur_vrhel
load T_xyz1931

S_out = [380,1,401];

spd_D65 = SplineSpd(S_D65,spd_D65,S_out,1);
S_D65 = S_out;

sur_vrhel = SplineSrf(S_vrhel,sur_vrhel,S_out,1);
S_vrhel = S_out;

T_xyz1931 = SplineCmf(S_xyz1931,T_xyz1931,S_out,1);
S_xyz1931 = S_out;

colourSignals = sur_vrhel.*spd_D65;
norm = (T_xyz1931(2,:)*spd_D65)/100; % to normalise Y to 100 for white
XYZ_D65 = (T_xyz1931*spd_D65)/norm; % not exactly the same as listed online but it'll do for this
XYZ = (T_xyz1931*colourSignals)/norm;

LAB = XYZToLab(XYZ,XYZ_D65);

%% Prep values for plotting

xyY = XYZToxyY(XYZ);
%DrawChromaticity
%scatter(xyY(1,:),xyY(2,:),'filled','k','MarkerFaceAlpha',0.2);

%% LAB -> XYZ

clc

XYZ_PTB = LabToXYZ(LAB,XYZ_D65);
XYZ_IMT = lab2xyz(LAB','WhitePoint',XYZ_D65'); %IMT for 'image toolbox'

devInd_XYZ = all(XYZ_PTB ~= XYZ_IMT');
deviation_XYZ = max(abs(XYZ_PTB - XYZ_IMT'));
fractionalDeviation_XYZ = deviation_XYZ/mean(abs(XYZ_PTB(:)));

figure,
DrawChromaticity, hold on
scatter3(xyY(1,:),xyY(2,:),xyY(3,:),'filled','k','MarkerFaceAlpha',0.1);
scatter3(xyY(1,devInd_XYZ),xyY(2,devInd_XYZ),xyY(3,devInd_XYZ),...
    [],fractionalDeviation_XYZ(devInd_XYZ),'filled')
zlabel('Y')
daspect([1,1,100])
view(3)
colormap('cool')
cb = colorbar;
ylabel(cb, 'fractionalDeviation\_XYZ')

%% XYZ -> sRGBlin

sRGBlin_PTB = XYZToSRGBPrimary(XYZ);
sRGBlin_IMT = xyz2rgb(XYZ','ColorSpace','linear-rgb');

devInd_sRGBlin = all(sRGBlin_PTB ~= sRGBlin_IMT');
deviation_sRGBlin = max(abs(sRGBlin_PTB - sRGBlin_IMT'));
fractionalDeviation_sRGBlin = deviation_sRGBlin/mean(abs(sRGBlin_PTB(:)));

figure,
DrawChromaticity, hold on
scatter3(xyY(1,:),xyY(2,:),xyY(3,:),'filled','k','MarkerFaceAlpha',0.1);
scatter3(xyY(1,devInd_sRGBlin),xyY(2,devInd_sRGBlin),xyY(3,devInd_sRGBlin),...
    [],fractionalDeviation_sRGBlin(devInd_sRGBlin),'filled')
zlabel('Y')
daspect([1,1,max(xyY(:))])
view(0,0)
colormap('cool')
cb = colorbar;
ylabel(cb, 'fractionalDeviation\_sRGBlin')

%% sRGBlin -> sRGB

sRGB_PTB = uint8(SRGBGammaCorrect(sRGBlin_PTB/100,0)'); % unclear where the factor of 100 comes from but it needs it...
sRGB_IMT = lin2rgb(sRGBlin_PTB/100,'OutputType','uint8');

devInd_sRGB = all(double(sRGB_PTB) ~= double(sRGB_IMT'),2)'; %need some transposing for some reason
deviation_sRGB = max(abs(double(sRGB_PTB) - double(sRGB_IMT')),[],2);

figure,
DrawChromaticity, hold on
scatter3(xyY(1,:),xyY(2,:),xyY(3,:),'filled','k','MarkerFaceAlpha',0.1);
scatter3(xyY(1,devInd_sRGB),xyY(2,devInd_sRGB),xyY(3,devInd_sRGB),...
    [],deviation_sRGB(devInd_sRGB),'filled')
zlabel('Y')
daspect([1,1,max(xyY(:))])
colormap('cool')
cb = colorbar;
ylabel(cb, 'fractionalDeviation\_sRGB')

%% vis (for fun)

figure,
image(permute(sRGB_PTB,[1,3,2]))
```

![sRGBdebugging4](https://user-images.githubusercontent.com/3739866/135674456-4fa970da-8992-4589-8dae-0c8852c03042.png)
![sRGBdebugging5](https://user-images.githubusercontent.com/3739866/135674457-e0543815-9480-44fe-bd7b-60ffd153e28d.png)
![sRGBdebugging6](https://user-images.githubusercontent.com/3739866/135674459-94bde88f-a1c6-4d3a-a20c-8845e6bd4e20.png)


![sRGBdebugging7](https://user-images.githubusercontent.com/3739866/135674453-1f4e422e-af82-4764-841b-33bd661260b2.png)

**Comment by da5nsy** [comment] 2021-10-02 16:53
An update on the linearization deviations:

When I replace the stimulus set with a large number of random XYZ values (`sz = [1,5000]; XYZ = [rand(sz)*100;rand(sz)*100;rand(sz)*100];`), I see more subtleties in the structure of the deviations at the **XYZ -> linear sRGB** stage:
![sRGBdebugging8](https://user-images.githubusercontent.com/3739866/135724285-0d3f46c3-8a92-4aa9-bb33-f72333658891.png)
(best seen in 3D by rotating around the plot)

---

Curiously, if I use the `xyz2rgb` as a 'one-step' (rather than `xyz2rgb(XYZ','ColorSpace','linear-rgb')` followed by `lin2rgb`) I get a pattern of deviations at the edge of the sRGB gamut:
![sRGBdebugging9](https://user-images.githubusercontent.com/3739866/135725512-d2c435e7-6415-42ef-b724-a1f24b1a65e6.png)

Code: https://github.com/da5nsy/General-Purpose-Functions/blob/4adaa6422fabbc3946ee6cf158bc3cd998234ee5/ComparingLabtosRGB.m

**Comment by DavidBrainard** [comment] 2021-10-04 15:06
I looked for my sRGB standard document but have not been able to find it.  I will try to go through all this carefully, but it may be a little while.  My guess remains that the differences have to do with slight differences in expression of the standard, but not totally sure.

**Comment by da5nsy** [comment] 2021-10-04 15:46
One thing that has come up for me recently that I'm struggling to work out, and might be a bit of a smoking gun is:

```
LAB = [70,0,0];

RGB_IMT_D50 = lab2rgb(LAB,'whitepoint','D50','OutputType','uint8')

RGB_IMT_D65 = lab2rgb(LAB,'whitepoint','D65','OutputType','uint8')
```
`RGB_IMT_D50 = [171,171,171]`
`RGB_IMT_D65 = [171,171,171]`

whereas:
```
LAB = [70,0,0];

XYZ_PTB_D50 = LabToXYZ(LAB',whitepoint('d50')');
sRGBlin_D50 = XYZToSRGBPrimary(XYZ_PTB_D50);
sRGB_PTB_D50 = uint8(SRGBGammaCorrect(sRGBlin_D50,0)');

XYZ_PTB_D65 = LabToXYZ(LAB',whitepoint('d65')');
sRGBlin_D65 = XYZToSRGBPrimary(XYZ_PTB_D65);
sRGB_PTB_D65 = uint8(SRGBGammaCorrect(sRGBlin_D65,0)');
```
`RGB_PTB_D50 = [184,169,148]`
`RGB_PTB_D65 = [171,171,171]`

It looks like the IMT version either doesn't respect the illuminant, or includes an extra CAT.

**Comment by kleinerm** [comment] 2023-09-22 17:32
Closing due to inactivity.

**Closed by kleinerm** 2023-09-22 17:32 UTC
