### ISSUE TITLE
Inconsistent Alpha from Procedural Gratings

### ISSUE THREAD

**Issue by mrkrause** [Psychtoolbox-3/Psychtoolbox-3#505] opened 2018-10-03 22:38 UTC
I'd like to report two possible issues, both having to do with the alpha of procedurally-generated textures.

1. The "basic" sine grating generated by [`CreateProceduralSineGrating`](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychGLImageProcessing/CreateProceduralSineGrating.m) appears to have its alpha channel modulated along with the brightness:  areas with low luminance have low alphas, bright areas are less transparent. When these are drawn against a non-black background, the grating is therefore distorted. At the same time, I'm struggling to imagine a good use for this behavior, so it seems like this might be a bug (and easy to fix in the shader).

2. As a partial consequence of that, the output of [`CreateProceduralSmoothedAperatureSineGrating`](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychGLImageProcessing/CreateProceduralSmoothedApertureSineGrating.m) depends how the `radius` parameter is set. If radius is set to inf to draw a square (the default), `CreateProceduralSineGrating` is called and the alpha distortion happens. If a value is provided, a different shader is called and the grating is fully opaque. Regardless of whether you think the alpha should be affected or not, changing the radius parameter should not change the apparent contrast of the grating! See attached [script](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/2444264/drawtest.m.txt) and the screenshot below (the moire is from my cellphone camera). 

![ptb_alphabug](https://user-images.githubusercontent.com/3977675/46443230-95335500-c73a-11e8-8e07-2a74c8477b1c.JPG)

My preference would be to change the shaders so that both types of gratings produce opaque gratings. On the other hand, I recognize that CreateProceduralSineGrating has been around for a while and, if people are depending on this, it might be better to change the the SmoothedAperatureSineGrating shader to match the others. 

I'm happy to contribute patches either way.

**Comment by kleinerm** [comment] 2018-10-30 04:29
Wrt. 1, it's not a bug, it is meant to allow alpha channel modulation when one uses alpha blending. Iff alpha is actually modulated can be controlled via the 'modulateColor' parameter to Screen('DrawTexture'), e.g., a modulatecolor = [1,1,1,0]; would stop alpha-modulation.

Wrt. 2. The inconsistency should only happen if 'useAlpha' parameter is set to the non-default value of 1, which both our only demo and your script does. Here there is the question if the useAlpha 1 else code branch should be fixed in the shader to make it consistent if that is meaningfully doable, also adding the alpha Offset that i assume got accidentally stripped away? @iandol any opinion?

Changing the default behavior of the shaders after many years is not a good idea.

In any case, maybe we should document the behavior better in the help texts, as this can indeed be surprising that the modulation is essentially applied twice if one uses alpha blending, but doesn't select the modulateColor and BackgoundColor offset parameters accordingly.

Patches for that welcome.

**Comment by iandol** [comment] 2018-10-31 09:13
Yes, we shouldn't change CreateProceduralSineGrating behaviour. And yes, I think it would be better to align SmoothedAperatureSineGrating to do what the normal grating shader does by default (i.e. allow alpha modulation without modulateColour applied). That is established behaviour.

I think a better description about what happens in the interactions between blending modulateColor and backgroundColor would be welcome. I suspect the fact I didn't quite understand this originally is why I wrote the smoothed edge shader the way I did (i.e. I also expected alpha applied once from the edge in where a contrast of 1 ends up looking correct) 😬— I still don't always have an intuitive understanding of OpenGL blending, I end up trial and error'ing my way through getting OpenGL blending to do what I want... But I'm also happy to help to add some text to the help once we decide what to do.

**Closed** 2020-03-25 20:23 UTC
Labels: enhancement, question
