### ISSUE TITLE
[Paid Support Request] Issue rendering “small” font sizes with TextAntiAliasing Disabled

### ISSUE THREAD

**Issue by paretech** [Psychtoolbox-3/Psychtoolbox-3#785] opened 2022-10-18 21:39 UTC
**Describe the bug**

During development of an experiment, I ran across an issue where character ‘l’ (el) rendered as a series of horizontal lines instead of a filled vertical character. Other characters may also present artifacts under certain conditions but ‘l’ is definitely the most common offender. 

While our experiment is using different TextFont, TextSize, and TextStyle, I found that I could reproduce this issue using an unmodified version of DrawFormattedTextDemo.m provided that TextAntiAliasing is disabled prior to execution. See steps below to reproduce.

- TextAntiAliasing: Disabled (i.e. 0)
- TextFont: ‘Courier New’
- TextSize: 14
- TextStyle: 1+2

I also confirmed that I can reproduce with a modified version of DrawManuallyAntiAliasedTextDemo.m provided that FontStyle=1+2, FontSize=14px (or less), and TextAntiAliasing is again disabled. I would be happy to provide my modified version if helpful, otherwise I assume the unmodified DrawFormattedTextDemo.m along with the confirmation of parameters will suffice. 

If you try other methods/variations in attempt to reproduce, note that different font families and font styles may require different font size before issue will present. For example, if I change TextStyle to 0, with TextFont ‘Courier New’, you may need to reduce the TextSize to 10 for the issue to present.

I have attached “diary” output while performing the “steps to reproduce” section below with PTB Verbosity set to level 5. The only line item I see greater than INFO level is “PRB-WARNING: DrawText: Failed to load external drawtext plugin [...] libptbdrawtext_ftgl.so.1: wrong ELF class: ELFCLASS32]. Retrying under generic name [libptbdrawtext_ftgl.so.1]” but in the console window where I launched MATLAB I see debug output that seems to me to indicate that it recovered successfully “libptbdrawtext_ftgl: External ‘DrawText’ text rendering plugin initialized”.

I did spend some time searching the internet and forums for possible solutions. Most of the posts I found were more related to disabling TextAntiAliasing or positioning/bounding text rather than issues/artifacts in rendering text. 

Note that the experiment I am developing requires TextAntiAliasing be disabled and specific font sizes used so it is important to our team to find a solution to this issue or to start pursuing workarounds. I would like to use some of our remaining support for this issue, our next authorization token is. 

**F5P6CUU9-20221018141725:2ffb14e8955d87b82ff94953a2c6c6383b0f4d7216091be5a46352cdb5a9014d**

Thank you all for the hard work on this project and for your help with my question. I couldn’t imagine making these experiments without community and tools like yours. 

Sincerely,

Matt Pare

Meta Reality Labs

**To Reproduce**

1. Start computer, MATLAB 
2. From MATLAB command window, run `Screen(‘Preference’, ‘TextAntiAliasing’, 0);`
3. From MATLAB command window, run `DrawFormattedTextDemo`

**Expected behavior**

Observe in onscreen graphic output from above steps to reproduce where text with 'l' is rendered as series of horizontal lines (see attached screenshot). No distortion of 'l' was expected.

**Screenshots**

These screenshots may appear like I'm trying to render impossibly small fonts, but when I use the experiment font the issue starts to present at larger font sizes (e.g. 20 px tall). 

![20221018T143631_woff_14](https://user-images.githubusercontent.com/209955/196550231-438fb6be-5a25-455d-89e9-c8bf2cee6a65.png)

<img width="772" alt="20221018T143631_woff_14_zoom" src="https://user-images.githubusercontent.com/209955/196550724-689fafb3-4a64-4198-91d7-301b615bdfb3.png">

![20221018T101732](https://user-images.githubusercontent.com/209955/196550260-c239ddca-fc99-4fe7-bc66-afe88501f8b4.png)

**Desktop (please complete the following information):**
 - OS: "Linux fedora 5.17.12-100.fc34.x86_64 #1 SMP PREEMPT Mon May 30 17:47:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
 - Runtime: MATLAB R2021b (9.11.0.1769968), 64-bit (glnxa64), September 17, 2021
 - Hardware
   - Memory: 128 GB RAM
   - Processor: AMD Ryzen threadripper pro 3975wx32-coresx64
   - Graphics: AMD Radeon rx 6900 xt
 - PTB Version: 3.0.18 - Flavor: Manual Install, 21-May-2022 21:28:27

**Additional context**

See attached diary log [20221018_font_issue_log.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/9815294/20221018_font_issue_log.txt).

**Comment by kleinerm** [comment] 2022-10-22 05:47
You make beautiful bug reports!

This required a lot of debugging to track it down and to develop a workaround - Over 8 hours, more than what the remaining support licenses covered, so all ten paid support licenses are now used up. At least the workaround is simple and effective.

Anyway, turns out this is a bug in the Mesa open-source OpenGL drivers, affecting pretty much all gpu's under Linux,
present since at least October 2010, but apparently not noticed by anyone, given it hits a niche case inside a niche case.
Essentially you need to draw aliased text where glyph images must be narrower than 8 pixels, hence affecting narrow letters
like l, or ! or | or similar at small text sizes.

I will probably submit a proper bug fix to Mesa upstream some time when i get around it.

For now i've implemented a rather simple workaround inside ptb's drawtext plugin, which should not have any measurable
impact on performance and fixes the bug as tested on AMD and Intel. Commit with bug fix and explanations here:
https://github.com/kleinerm/Psychtoolbox-3/commit/0c5def74cb789a0b53e67c57ccb232671c027fba

This will be part of the upcoming 3.0.19 ptb release somtime November.

Until then you can grab the new 64-Bit `libptbdrawtext_ftgl64.so.1`plugin for Intel cpu's as a replacment for the one inside
`Psychtoolbox/PsychBasic/PsychPlugins/` from the following link:

https://github.com/kleinerm/Psychtoolbox-3/raw/master/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.so.1

Hope it helps.

**Comment by kleinerm** [comment] 2022-10-22 17:19
Btw. two comments to your post:

That "...wrong ELF class: ELFCLASS3..." at high verbosity is normal. It probes for 32-Bit Intel plugins first, then for 64-Bit plugins, so on a 64-Bit system it will always complain that the 32 bit lib it found first is unsuitable on 64-Bit systems. Just debug chatter...

Wrt. to actually chosen text font: If you want to really know which font you are using, it is advisable to call something like ``actualFont = Screen('TextFont', window)`` **after the first actual text drawing or text bounds call**, e.g., ``Screen('DrawText'), Screen('TextBounds'), DrawFormattedText()`` etc. Because switching fonts / font sizes / font styles etc. can be quite an expensive operation, commands like ``Screen('TextFont', window, font)`` do not really select the font immediately, just store required font name / properties internally for later use. Only the first time a font is really needed, for drawing actual text or calculating its bounding boxes, will the fontmapping start, where the text renderer plugin will try to find a suitable font for requested font family, size, style etc. in the systems collection of fonts. We use libfontconfig for this. If fontconfig can't find a perfect match, it will select the closest matching installed font, by some metrics of closeness. This is a bit of trap if one doesn't think about it: While our text renderer is identical on all operating systems and should therefore render identically (assuming no bad OpenGL graphics driver bugs etc.), the set of default fonts on Linux, Windows and macOS differs and varies widely depending on OS, Linux distribution, Windows/macOS version etc! Rarely ever does choice of "Times New Roman" or "Geneva" actually map really to "Times New Roman" or "Geneva", but to some close substitute. Calling ``Screen('Textfont', window);`` **after** the first actual drawn text string will report back the actual chosen font family name etc. Cfe. `DrawSomeTextDemo.m`. There's also lots of fontmapping debug output at higher verbosity levels, at least under Octave, or when one launches Matlab from a terminal window (in the terminal window).

Even the same fonts, ie. same font family name, may not come from the same font designer on different operating systems, i assume. So i guess if you really want tight control over this, you'd have to install your own font file on all machine+operating system combos you want to run your studies on.

**Comment by paretech** [comment] 2022-10-22 18:21
Thank you for looking into this Mario. Your response and the additional context is much appreciated. I will evaluate the workaround first thing Monday morning. I'll also start the process with our procurement team to replenish paid support. 

Have a good weekend Sir,
-Matt

**Comment by paretech** [comment] 2022-10-25 18:11
Hi Mario, 

I wanted to let you know that I've loaded the [new 64-Bit libptbdrawtext_ftgl64.so.1plugin](https://github.com/kleinerm/Psychtoolbox-3/raw/master/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.so.1). 

I don't have much time running the replacement plugin yet, but my initial inspection of output from a handful of test cases is looking good! I'm no longer seeing the artifacts on small aliased fonts with narrow glyphs. This is fantastic, thank you SO much! 

I'll continue to run this replacement plugin on a dev PC for a bit. Before moving over to production system I'll probably do some inspection of commit history to get a better idea of what other changes are present in the replacement libptbdrawtext_ftgl64.so.1 plugin. I need to be careful with changes to the production system as we have a series of user studies in progress. Just some due diligence to insure minimum risk of inducing small changes to text rendering, alignment or other side effects. 

Do you need or want me to change status, tags or anything else related to this issue?

Either way, I'll try to report back here after I get some additional runtime, but we are very happy right now.

Thank you again Sir,
-Matt

**Comment by kleinerm** [comment] 2022-10-25 18:30
Great! The commit history for the plugin is here:

https://github.com/kleinerm/Psychtoolbox-3/commits/master/PsychSourceGL/Cohorts/FTGLTextRenderer

As you'll see, there hasn't been any change for almost exactly 2 years, since the initial 3.0.17.0 PTB release, where the ability for HDR color ranges was added as part of our general HDR enablement on Linux and Windows. This should be in that sense a very safe change (famous last words)...

That said, the main sources of potential variability or regressions for text drawing are not in PTB, but its dependencies libfontconfig for font matching/selection, libfreetype for converting fonts into rasterized / (anti-aliased) glyph images, and as we just learned, the OpenGL graphics drivers of the system. Also fonts itself, if OS vendors switch fonts etc.

Nothing new here. But another reason among many why I push for use of open-source operating systems, ie. Linux, as more of the whole stack is inspectable/documented, and fixable if needed, time/resources/skills permitting. This issue should auto-close on release of PTB 3.0.19.0, sometime in November.

Have a good day,
-mario

**Closed** 2023-02-17 06:20 UTC
Labels: bug, notourbug, needspriosupportpayment
