### ISSUE TITLE
CRS T-Lock drawn incorrectly in Mono++ mode

### ISSUE THREAD

**Issue by robertlee-crs** [Psychtoolbox-3/Psychtoolbox-3#807] opened 2023-06-20 10:01 UTC
**Describe the bug**
In certain hardware/software configurations, when using a CRS Display++ in Mono++ with CLUT overlay, the T-Lock line is drawn in the wrong place(offset by one pixel). This results in the T-Lock line being not recognised and CLUT features not working, most obviously when running BitsSharpIdentityClutTest. Other modes seem ok. This happens with an AMD Radeon RX500 and the open-source drivers on Ubuntu (and was initially reported to me by a customer using a Radeon Pro WX 5100 and the AMD proprietary drivers). Using Vulkan mode gives the correct output. Swapping the GPU for a NVidia GTX 1060 and the NVidia proprietary drivers, on the the same machine, gives the correct output (with some timing issues).

**To Reproduce**
Run: BitsSharpIdentityClutTest - test image is greyscale with visible T-Lock line
Run: BitsPlusIdentityClutTest([],[],[],1) - test image is correct.
Run: BitsPlusIdentityClutTest([],[],[],[],1) - test image is correct.
Run BitsPlusIdentityClutTest([],[],rect) with rect argument to shift window one pixel to right - test image is correct.
Using any code using Mono++ with overlay gives wrong overlay colours (unrecognised T-Lock). Adding PsychImaging('AddTask', 'General', 'UseVulkanDisplay'); seems to fix it (but I don't know what other problems that might introduce).

**Desktop:**
 - OS: Ubuntu Linux 22.04.2 LTS
 - Runtime: Matlab R2023a
 - Hardware: AMD RX550, open source driver shipped with Ubuntu
 - Version: Psychtoolbox 3.0.19

**Additional information**
This has worked before, so must be a fairly recently introduced problem.

**Comment by kleinerm** [comment] 2023-09-14 22:38
BitsSharpIdentityClutTest is not a PTB function, I don't know what it is.

Testing BitsPlusIdentityClutTest on Ubuntu 22.04.2 LTS + Linux 5.19 + Mesa 22.2.5, and after upgrade to Ubuntu 22.04.3 LTS + Linux 6.2 + Mesa 23.0.4 on my AMD gpu's with a Bits# at 1920x1080 at 60 Hz showed no problems at all. One of the gpu's was from the same polaris gpu family as your mentioned gpu's, the other a more modern Raven Ridge integrated gpu.

So after over 2 hours of work time, I can't reproduce these problems at all.

Any further help with this issue would require back-pay for the 2 spent work hours and at least one more hour for additional work.

**Comment by kleinerm** [comment] 2024-02-16 16:41
Presumably fixed since PTB 3.0.19.6 by above commit. Closing.

**Closed by kleinerm** 2024-02-16 16:41 UTC
Labels: needspriosupportpayment
