### ISSUE TITLE
MacOS Catalina - ! PTB - ERROR: SYNCHRONIZATION FAILURE !

### ISSUE THREAD

**Issue by Shalambe** [Psychtoolbox-3/Psychtoolbox-3#670] opened 2020-07-10 17:47 UTC
Hello everyone,

I'm trying to run an experiment in the psychtoolbox on macOS Catalina (version 10.15.3). The code is widely used and tested in our lab, however, I can't even try it out because of the synchronization failure error. Once it gets to the screen presentation it crashes my Matlab and can exit the screen only by force quitting it. 

I know this is a well-known issue and that newer operating systems are not officially supported and I've read some very desperate comments about macOS bugs in this regard :) I read #SyncTrouble and tried suggested solutions/tests. I also read that updated versions of PTB should have fixed this issue. I'm using the latest PTB version and tried it on Matlab R2018a, R2019a, and R2020a as well. 

I'm not very experienced in all this yet and maybe missing something very simple. I tried all solutions I could find online though. I'm copying the screen presentation part of the script and the whole error message. I'll provide any other information if needed, in hope that maybe there are some new solutions found and you know how I can proceed. 

PsychDefaultSetup(2); Screen('Preference', 'SkipSyncTests', 1); 
screenNumber = max(Screen('Screens'));
white = WhiteIndex(screenNumber); grey = white / 2; black = BlackIndex(screenNumber);
% Open the screen
%[w, screenRect] = Screen('OpenWindow', screenNumber, bgcolour, [], 32, 2); %Crash !!!
% For testing:
[w, screenRect] = Screen('OpenWindow', screenNumber, bgcolour, [0 0 640 480]);

______________________________________________________________________________________________

PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.16 - Build date: Apr 26 2020).
PTB-INFO: OS support status: OSX version 10.15 is not officially supported or tested at all for this release.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel(R) UHD Graphics 617 :: 2.1 INTEL-14.4.23
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 5376 MB of texture memory.
PTB-INFO: VBL startline = 1800 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.353281 ms [61.149809 Hz]. (61 valid samples taken, stddev=2.380794 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-WARNING: ==================================================================================================================
PTB-WARNING: DESKTOP COMPOSITOR IS ACTIVE! ALL FLIP STIMULUS ONSET TIMESTAMPS WILL BE VERY LIKELY UNRELIABLE AND LESS ACCURATE!
PTB-WARNING: STIMULUS ONSET TIMING WILL BE UNRELIABLE AS WELL, AND GRAPHICS PERFORMANCE MAY BE REDUCED!
PTB-WARNING: DO NOT USE THIS MODE FOR RUNNING REAL EXPERIMENT SESSIONS WITH ANY REQUIREMENTS FOR ACCURATE TIMING!
PTB-WARNING: ==================================================================================================================

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! -----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 33793 ...
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus drawing.
PTB-INFO: Enabling panel fitter. Providing virtual framebuffer of 640 x 480 pixels size.
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus post-processing (if any).
>> sca

WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.

(The message is copied after using a test window and not a full screen, I can't see any message for the full-screen window presentation since it freezes the screen and no key combination (Ctrl+C, Alt+Tab, and sca) is helping, except force quitting Matlab)

Any suggestions and ideas would be very valuable!

Thanks,
Tamari

**Comment by dcnieho** [comment] 2020-07-10 19:57
I can't help with this specific issue, but had a note regarding key
combinations. Isn't it apple+. to end script execution? and then something
like apple+0 to put focus in the command window?

On windows i use:
1. cntr+c
2. cntr+0
3. sca enter

That almost always works ;) There is hopefully some mac equivalent for that
that doesn't send your sca into oblivion.

**Comment by kleinerm** [comment] 2020-07-11 06:48
The current PTB 3.0.16 beta should work ok'ish on the Catalina trainwreck v 10.15.3. However, testing was done on AMD graphics, and Apple manages to screw up something new with every point release, so...

A fullscreen window should work with best timing. And if it doesn't, the SkipSyncTest 1 setting you use should keep it going. You can use the 'diary on' command to collect output into a diary text file, even if you can't see the command window. If you only end with a hanging window in your own code, and not with our standard demos, e.g., DotDemo, LinesDemo, PerceptualVBLSyncTest etc., then that suggest not a timing problem, but some bug in your code. Use of try and catch statements helps to get the window closed in case of an error abort, as shown in many of our demos.

**Comment by Shalambe** [comment] 2020-07-11 16:24
Thanks for the note.

I believe the key combination I mentioned above is doing the same on Mac. 

Ctrl-C - interrupting the script
Apple (Command) key + Tab - focus the cursor to command line
sca - close the window

> I can't help with this specific issue, but had a note regarding key combinations. Isn't it apple+. to end script execution? and then something like apple+0 to put focus in the command window? On windows i use: 1. cntr+c 2. cntr+0 3. sca enter That almost always works ;) There is hopefully some mac equivalent for that that doesn't send your sca into oblivion.
> […](#)

**Comment by Shalambe** [comment] 2020-07-11 16:56
> The current PTB 3.0.16 beta should work ok'ish on the Catalina trainwreck v 10.15.3. However, testing was done on AMD graphics, and Apple manages to screw up something new with every point release, so...
> 
> A fullscreen window should work with best timing. And if it doesn't, the SkipSyncTest 1 setting you use should keep it going. You can use the 'diary on' command to collect output into a diary text file, even if you can't see the command window. If you only end with a hanging window in your own code, and not with our standard demos, e.g., DotDemo, LinesDemo, PerceptualVBLSyncTest etc., then that suggest not a timing problem, but some bug in your code. Use of try and catch statements helps to get the window closed in case of an error abort, as shown in many of our demos.

Many thanks for the response!

The Demos you mentioned are working perfectly and the window I'm seeing when executing the script is standard PTB window. When it crashes it shows an exclamation mark in a triangle and then the screen is not responsive. Thanks for suggesting to use the diary, I did so and the error message is the same on a full-screen as on the test window -----! PTB - ERROR: SYNCHRONIZATION FAILURE! -----

I tried several tests (Mentioned in SynchTrouble) again and found out that only the PerceptualVBLSyncTest is working. VBLsync and OSXCompositorIdiocyTest both crash Matlab again. In the error message, it says: 

"Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback". 

Then I tried BeampositionTest and I see message saying that 

"Beamposition queries broken or disabled or unsupported on your setup!"

Can this be a reason for my issue? I was reading BeampositionQueries documentation now and there are some suggestions to fix that, however wanted to make sure that's the right way to go, before jumping in trying new solutions. One suggestion is to install PsychtoolboxKernelDriver but it also says the Intel Graphic cards are not supported. So not sure how to proceed. 

I tried adding this setting: Screen(‘Preference’,’VBLTimestampingmode’, 1); but it did not change anything.

Thanks again,
Tamari

**Comment by kleinerm** [comment] 2020-07-11 19:40
> > The current PTB 3.0.16 beta should work ok'ish on the Catalina trainwreck v 10.15.3. However, testing was done on AMD graphics, and Apple manages to screw up something new with every point release, so...
> > A fullscreen window should work with best timing. And if it doesn't, the SkipSyncTest 1 setting you use should keep it going. You can use the 'diary on' command to collect output into a diary text file, even if you can't see the command window. If you only end with a hanging window in your own code, and not with our standard demos, e.g., DotDemo, LinesDemo, PerceptualVBLSyncTest etc., then that suggest not a timing problem, but some bug in your code. Use of try and catch statements helps to get the window closed in case of an error abort, as shown in many of our demos.
> 
> Many thanks for the response!
> 
> The Demos you mentioned are working perfectly and the window I'm seeing when executing the script is standard PTB window. When it crashes it shows an exclamation mark in a triangle and then the 
screen is not responsive. Thanks for suggesting to use the diary, I did so and the error message is the same on a full-screen as on the test window -----! PTB - ERROR: SYNCHRONIZATION FAILURE! -----
> 

The exclamation mark in a triangle is a visual warning of sync trouble, but it won't abort your script. If our demos work after showing the warning triangle then all there is is timing problems, and the reason for the unresponsive screen after the triangle is a bug in your script, which causes it to abort with some error. Proper use of try-catch will in such cases close the window and allow to see the error message.

You need something like

try
  your code
catch
  sca;
  rethrow(lasterror);
end

or at the top of your main script:

canary = onCleanup(@sca)

to automatically close the windows when your script terminates or aborts due to an error.

If Matlab doesn't show an error message for some reason, type ple (for print-last-error) to reprint the last error.

> I tried several tests (Mentioned in SynchTrouble) again and found out that only the PerceptualVBLSyncTest is working. VBLsync and OSXCompositorIdiocyTest both crash Matlab again. In the error message, it says:
> 
> "Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback".
> 
> Then I tried BeampositionTest and I see message saying that
> 
> "Beamposition queries broken or disabled or unsupported on your setup!"
> 
> Can this be a reason for my issue? I was reading BeampositionQueries documentation now and there are some suggestions to fix that, however wanted to make sure that's the right way to go, before jumping in trying new solutions. One suggestion is to install PsychtoolboxKernelDriver but it also says the Intel Graphic cards are not supported. So not sure how to proceed.
> 

The PsychtoolboxKernelDriver on machines with Intel gfx still works, but there's an unknown theoretical chance it could cause machine crashes/lockups/damage, so even if you install it, you need to set an extra flag to enable its use. Otoh. so far no such malfunctions were observed by myself, and without the kernel driver in use all visual stimulation timing has to be considered completely untrustworthy. Iow., without it, a mac with Intel graphics should not be used at all for data collection if timing matters.

If our scripts work and yours doesn't then it is a bug in your script after the Screen('Openwindow',..) statement. What also helps for debugging is calling the command PsychDebugWindowConfiguration before running the script. That would disable all timing tests and show everything half-transparent, so you can still see the command window and type commands after your script aborts.

If all scripts give the red triangle warning, then the timing of your machine is unusable for unknown reasons and if the tips in our troubleshooting instructions don't work, though luck. After all the Catalina trainwreck is not recommended for a good reason. Use of Apple computers is generally not recommended for serious work, given Apples shoddy software and hardware quality. Installing the kernel driver may give extra clues to the reason for the sync failures.

**Comment by Shalambe** [comment] 2020-07-14 16:41
> > > The current PTB 3.0.16 beta should work ok'ish on the Catalina trainwreck v 10.15.3. However, testing was done on AMD graphics, and Apple manages to screw up something new with every point release, so...
> > > A fullscreen window should work with best timing. And if it doesn't, the SkipSyncTest 1 setting you use should keep it going. You can use the 'diary on' command to collect output into a diary text file, even if you can't see the command window. If you only end with a hanging window in your own code, and not with our standard demos, e.g., DotDemo, LinesDemo, PerceptualVBLSyncTest etc., then that suggest not a timing problem, but some bug in your code. Use of try and catch statements helps to get the window closed in case of an error abort, as shown in many of our demos.
> > 
> > 
> > Many thanks for the response!
> > The Demos you mentioned are working perfectly and the window I'm seeing when executing the script is standard PTB window. When it crashes it shows an exclamation mark in a triangle and then the
> > screen is not responsive. Thanks for suggesting to use the diary, I did so and the error message is the same on a full-screen as on the test window -----! PTB - ERROR: SYNCHRONIZATION FAILURE! -----
> 
> The exclamation mark in a triangle is a visual warning of sync trouble, but it won't abort your script. If our demos work after showing the warning triangle then all there is is timing problems, and the reason for the unresponsive screen after the triangle is a bug in your script, which causes it to abort with some error. Proper use of try-catch will in such cases close the window and allow to see the error message.
> 
The exclamation mark in a triangle I can see only using test window and after that the screen freezes on a grey screen and is not responsive. On the full-screen it freezes on the grey screen without any other sign and either closes itself and shows "Mathwork crash reporter" window or does so after me force quitting Matlab (+ changes my display resolution every time at this point). Nothing else is working on the screen when it freezes on full-screen mode. I tried your suggestions, try-catch and canary = onCleanup(@sca) too and no change. After reopening Matlab if I try ple it says "no error message stored". 

I have loots of Matlab_crash_dump files but after contacting Mathworks with those, they refuse to help since it's a crash related to a toolbox created by third-party developers. Unfortunately I'm not very good in reading those crash files as well but one things that seemed interesting to me is that Matlab (or PTB?) somehow can't recognize the Graphic driver (or something like that)

Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : UTF-8
  Deployed                 : false
  Graphics Driver          : Unknown hardware 

Not sure if that can be a reason why I'm getting this error. 

> You need something like
> 
> try
> your code
> catch
> sca;
> rethrow(lasterror);
> end
> 
> or at the top of your main script:
> 
> canary = onCleanup(@sca)
> 
> to automatically close the windows when your script terminates or aborts due to an error.
> 
> If Matlab doesn't show an error message for some reason, type ple (for print-last-error) to reprint the last error.
> 
> > I tried several tests (Mentioned in SynchTrouble) again and found out that only the PerceptualVBLSyncTest is working. VBLsync and OSXCompositorIdiocyTest both crash Matlab again. In the error message, it says:
> > "Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback".
> > Then I tried BeampositionTest and I see message saying that
> > "Beamposition queries broken or disabled or unsupported on your setup!"
> > Can this be a reason for my issue? I was reading BeampositionQueries documentation now and there are some suggestions to fix that, however wanted to make sure that's the right way to go, before jumping in trying new solutions. One suggestion is to install PsychtoolboxKernelDriver but it also says the Intel Graphic cards are not supported. So not sure how to proceed.
> 
> The PsychtoolboxKernelDriver on machines with Intel gfx still works, but there's an unknown theoretical chance it could cause machine crashes/lockups/damage, so even if you install it, you need to set an extra flag to enable its use. Otoh. so far no such malfunctions were observed by myself, and without the kernel driver in use all visual stimulation timing has to be considered completely untrustworthy. Iow., without it, a mac with Intel graphics should not be used at all for data collection if timing matters.

Yeah, I've heard about mac not being very reliable for data collection. I just need to make it work on my laptop to adjust the experiment and create a new task. I'm going to run it in the lab computers on linux afterwards. 

> 
> If our scripts work and yours doesn't then it is a bug in your script after the Screen('Openwindow',..) statement. What also helps for debugging is calling the command PsychDebugWindowConfiguration before running the script. That would disable all timing tests and show everything half-transparent, so you can still see the command window and type commands after your script aborts.
> 

As I mentioned in the previous comment, some of your scripts work and some not. 

> If all scripts give the red triangle warning, then the timing of your machine is unusable for unknown reasons and if the tips in our troubleshooting instructions don't work, though luck. After all the Catalina trainwreck is not recommended for a good reason. Use of Apple computers is generally not recommended for serious work, given Apples shoddy software and hardware quality. Installing the kernel driver may give extra clues to the reason for the sync failures.

Thanks a lot for all the information. I really appreciate your help. I will try to work around a little more and will check with Mathworks forum regarding the crash report as well. I really hope I will be able to use PTB for experiment development soon :)

**Comment by denispelli** [comment] 2020-07-14 17:23
Hi Mario
Here, you said that "The current PTB 3.0.16 beta should work ok'ish on the Catalina trainwreck v 10.15.3."
**So is it ok to upgrade my machines from Mojave to Catalina?**
I'm using AMD drivers on MacBook Pros to get 11+ bit luminance precision.
Best
Denis

**Comment by kleinerm** [comment] 2020-07-16 15:20
@Shalambe ok, those Matlab crashes are real crashes, at least occasionally?

1. Maybe erase and redownload Psychtoolbox, to rule out some damaged files on your machine due to filesystem corruption or some corrupted download.

2. If the problem persists, copy one of those crash reports here.
3. Run a non-working script, using "diary on" and Screen('Preference','Verbosity', 100); before running it, and post the full output here.
4. Try to figure out which of OUR demos work and which don't and use that for steps 1 and 2. Maybe also run such a script with a PsychDebugWindowConfiguration call beforehand, that is like running it in windowed mode, without the need to change the code of the script.
5. Might also make sense to upgrade your train wreck to the latest 10.15.6 release from today. From what i've read it is also buggy as hell, truly deserving of the name trainwreck, just like every single Catalina release before it, but at least it might be different bugs. In the past, the iToys company at least managed to make the 10.x.6 release -- usually the final release for an OS -- ok, but apparently they are now also incapable of getting it right in 7 different iterations. Truly stunning.

**Comment by Shalambe** [comment] 2020-07-16 21:36
> @Shalambe ok, those Matlab crashes are real crashes, at least occasionally?
> 
Oh yes, they are very real :) 
> 1. Maybe erase and redownload Psychtoolbox, to rule out some damaged files on your machine due to filesystem corruption or some corrupted download.

I've done that. I've erased and downloaded whole Matlab (different versions) and then Psychtoolbox as well in those. 
> 2. If the problem persists, copy one of those crash reports here.

I will do this after trying out steps 3 and 4. Thanks for suggesting! 
> 3. Run a non-working script, using "diary on" and Screen('Preference','Verbosity', 100); before running it, and post the full output here.
> 4. Try to figure out which of OUR demos work and which don't and use that for steps 1 and 2. Maybe also run such a script with a PsychDebugWindowConfiguration call beforehand, that is like running it in windowed mode, without the need to change the code of the script.
> 5. Might also make sense to upgrade your train wreck to the latest 10.15.6 release from today. From what i've read it is also buggy as hell, truly deserving of the name trainwreck, just like every single Catalina release before it, but at least it might be different bugs. In the past, the iToys company at least managed to make the 10.x.6 release -- usually the final release for an OS -- ok, but apparently they are now also incapable of getting it right in 7 different iterations. Truly stunning.

I'll think about this too but I'm also kinda afraid :) I already regret upgrading macOS several months ago when I switched to mac from Windows, so I'm a little cautious about this.

**Comment by Shalambe** [comment] 2020-07-30 21:51
Many many thanks for help. I fixed it!

I tried 'diary on' with the non-working experiment code and the last record from the diary was this:

PTB-DEBUG: DrawText: Trying to load external text renderer plugin from following file: [ /Applications/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.dylib ]

I also tried several drawtext related demos and none of them were working. So I decided to try downloading Xquartz as it says in the PTB DrawTextPlugin documentation and it worked.  

I guess I had to start with diary and check the record at first place :) 

Thanks again!

**Comment by dcnieho** [comment] 2020-07-30 22:07
Glad its fixed!

**Closed by dcnieho** 2020-07-30 22:07 UTC

**Comment by kleinerm** [comment] 2020-08-04 20:53
Ok. Btw. i'd recommend rather installing GStreamer instead of that X11 server, because X11 will only give you high quality text rendering, whereas GStreamer also gives you all the multi-media functionality for the same amount of installation effort. I think i'll remove the reference to X11 from that help text for the next release.

It is very weird though that it crashed on you. It is not supposed to crash, just fall back to the lower quality/lower performance, more limited macOS specific text renderer. I just retested this on my MacBookPro with both 10.14.6 Mojave and 10.15.6 Catalina, Matlab R2019b, and couldn't reproduce any crashes or similar when i removed the libraries. Just a fallback to the old macOS text renderer, exactly as expected.

My MBP "survived" the upgrade to 10.15.6, but this wouldn't be macOS if no new things wouldn't be broken:

- Internal Retina display still works fine.
- External DisplayPort output is dead. Doesn't even detect the monitor.
- External HDMI works (for some resolutions, others give malfunctions/video dropouts/blue screens/snow), but gives "sync failures" and broken timing, no matter what one does.
- External DVI works, with apparently correct timing/timestamping, but identity pixel passthrough is totally and unfixably broken, making high precision visual simulators from VPixx or CRS completely unusable.
- At least VGA via USB-C -> VGA adapters seems to work without any issues, yay!

Nicely enough, same breakage now also under 10.14.6 Mojave, so i guess they screwed up the firmware even more. At least under Linux the same MBP still works pretty well.
Maybe the unexpected sync failures on your Intel gfx MBP are caused by similar problems and are not that unexpected anymore. At least it worked for six months or so, before the iMorons broke it again.

So i would also strongly recommend never updating a macOS ever, this is playing Russian roulette, and it is hardly ever getting better wrt. neuroscience applications. Unfortunately as PTB maintainer i don't have the option to avoid such updates infinitely, otherwise i surely would.
