### ISSUE TITLE
Verbosity not respected by IOPort

### ISSUE THREAD

**Issue by mermerico** [Psychtoolbox-3/Psychtoolbox-3#229] opened 2015-01-16 04:01 UTC
Trivial issue:
With verbosity set to 0, I still get

    IOPort-Info: Configuration for device com3:
    IOPort-Info: Current baud rate is 115200
    IOPort-Info: Baud rate changed to 115200

at the output. The statements come from line 571 in PsychSourceGL/Source/Windows/IOPort/PsychSerialWindowsGlue.c

There is a verbosity check associated with those lines so it seems the verbosity variable isn't being set correctly.

**Comment by kleinerm** [comment] 2015-02-03 13:23
Strange: Code seems to be perfectly fine, declaring extern int verbosity in the Windows code and defining int verbosity as non-static in core code. Maybe some weird linker error on the windows side?

Needs further investigation once i prepare a new Windows release at some point.

**Comment by kleinerm** [comment] 2015-03-07 22:14
This wasn't reproducible on my Windows VM, ie., a IOPort('Verbosity', 0); followed by a IOPort('OpenSerialPort', 'COM1') does suppress the error message for the non-existent COM1 port correctly, whereas the error message shows at default verbosity. Ergo the verbosity variable in PsychSerialWindowsGlue.c gets correctly set.

You can try with the rebuilt IOPort.mexw64 files from my kleinerm/Psychtoolbox-3 master branch, but for now closing this.

**Closed by kleinerm** 2015-03-07 22:14 UTC
Labels: invalid
