### ISSUE TITLE
Screen 'ConfigureDisplay','Brightness' should not produce fatal error

### ISSUE THREAD

**Issue by denispelli** [Psychtoolbox-3/Psychtoolbox-3#423] opened 2017-06-13 13:56 UTC
Hi Denis,

this is not a high priority bug of any urgency, so please file it in our GitHub Issue tracker so it doesn't get forgotten, and handled once i find time to work on such stuff.

https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues

...
thanks,
-mario

On 06/13/2017 04:41 AM, Denis Pelli wrote:
Dear Mario

Screen('ConfigureDisplay','Brightness',screen,screenOutput,brightnessSetting);

is useful, and typically works fine with the built-in display of a Mac. I accept that it doesn't work on all devices. However, the documentation provided by
Screen ConfigureDisplay?
claims that it will silently do nothing if not supported. In fact, a high school student today showed that it gives a fatal error on her Windows computer, and some time ago, when I tried it on my Mac while driving a video projector, it also gave a fatal error. We understand the OS doesn't always cooperate, so 'Brightness' can't work on all computers and displays. However, we hate fatal errors.

Ideally, 'Brightness' would fail gently, with a software flag, or provide a way to tell in advance whether this feature is supported.

Best
Denis

**Comment by kleinerm** [comment] 2017-06-26 18:38
Actually, nowhere does the help text for 'Brightness' claim it would fail silently, so this is not a bug. Marking as an enhancement request.

**Comment by denispelli** [comment] 2017-06-28 23:25
Thanks.


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>
<http://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>

**Closed** 2017-10-07 22:55 UTC
Labels: enhancement
