### ISSUE TITLE
flipVertical failing for DrawFormattedText

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#349] opened 2016-06-26 22:46 UTC
Hi Mario,

I just found that flipVertical is not working the way it should. It works if the text is vertically centered on the screen, but it soon leaves the screen if not. You can use the following code to see the problem.

```
clear all
try
    InitializeMatlabOpenGL;
    [wpnt,wrect] = PsychImaging('OpenWindow', 0,255);
    
    DrawFormattedText(wpnt,'ptest',900,400,0,'','','','',1);
    DrawFormattedText(wpnt,'ptest',1000,400,0,'',1,'','',1);
    DrawFormattedText(wpnt,'ptest',1100,400,0,'','',1,'',1);
    
    DrawFormattedText(wpnt,'ptest',900,'center',0,'','','','',1);
    DrawFormattedText(wpnt,'ptest',1000,'center',0,'',1,'','',1);
    DrawFormattedText(wpnt,'ptest',1100,'center',0,'','',1,'',1);
    
    Screen('Flip',wpnt);
    
    KbStrokeWait;
    sca
catch me
    sca
    rethrow(me)
end
```
Notice that the results from the third DrawFormattedText call are not on the screen, but from the 6th is fine.
I don't think this is something about the logic in DrawFormattedText, that is simple and seems right. Maybe something is up with the text drawer Screen('DrawText') or so, with this changed model matrix. 

All the best,
Dee
P.S. no idea why righttoleft is true in all my example calls, but the same issue happens if it is not.

**Comment by dcnieho** [comment] 2016-07-03 21:19
Note that this is with up-to-date PTB (Screen.mexw64 and libptbdrawtext_ftgl64.dll i downloaded from your personal repo on June 2nd). Windows 10. Matlab r2016a

**Comment by dcnieho** [comment] 2016-07-10 20:17
This still happens with a freshly updated PTB, 3.0.13

**Comment by dcnieho** [comment] 2016-07-31 22:13
Here is some further test code, trying multi-line texts as well (things are worse there, nothing is in the correct horizontal position).

`clear all

Screen('Preference', 'TextRenderer', 1);

try
    InitializeMatlabOpenGL;
    [wpnt,wrect] = PsychImaging('OpenWindow', 0,255);

    DrawFormattedText(wpnt,'ptest',900,200,0,'','','','',0);
    DrawFormattedText(wpnt,'ptest',1000,200,0,'',1,'','',0);
    DrawFormattedText(wpnt,'ptest',1100,200,0,'','',1,'',0);

    DrawFormattedText(wpnt,'ptest',900,'center',0,'','','','',0);
    DrawFormattedText(wpnt,'ptest',1000,'center',0,'',1,'','',0);
    DrawFormattedText(wpnt,'ptest',1100,'center',0,'','',1,'',0);

    DrawFormattedText(wpnt,'ptest\ntest',200,200,0,'','','','',0);
    DrawFormattedText(wpnt,'ptest\ntest',300,200,0,'',1,'','',0);
    DrawFormattedText(wpnt,'ptest\ntest',400,200,0,'','',1,'',0);

    DrawFormattedText(wpnt,'ptest\ntest',200,'center',0,'','','','',0);
    DrawFormattedText(wpnt,'ptest\ntest',300,'center',0,'',1,'','',0);
    DrawFormattedText(wpnt,'ptest\ntest',400,'center',0,'','',1,'',0);

    Screen('Flip',wpnt);

    KbStrokeWait;
    sca
catch me
    sca
    rethrow(me)
end
`

**Comment by dcnieho** [comment] 2016-07-31 22:36
Here is another test example. Took out a bit of the logic from DrawFormattedText, but using the correct bounding box (if you ask me). I draw both a string and a dot, both with and without the transformation matrix applied. The dot is vertically flipped just fine. the textbox and its center are correct too. So it seems something weird happens with the vertically flipped text rendering, but I'm not seeing the problem in this code.

```
clear all
Screen('Preference', 'TextRenderer', 1);

% PsychDebugWindowConfiguration;

txt = 'test';
[xp, yp] = deal(500,500);

try
    InitializeMatlabOpenGL;
    [wpnt,wrect] = PsychImaging('OpenWindow', 0,255);
    
    [~,bbox] = Screen('TextBounds', wpnt, txt,0,0,1);    % this bounding box is pixel-precise and relative to provided drawing cursor position (just what we need)
    textbox = OffsetRect(bbox, xp, yp);
    [xc, yc] = RectCenter(textbox);
    
    % draw text and dots without transformation matrices applied, see where
    % things should be showing up
    Screen('DrawText', wpnt, txt, xp, yp, [255 0 0], [], 1);
    Screen('DrawDots', wpnt, [xp, yp],5, [0 0 255]);
    Screen('DrawDots', wpnt, [xc, yc],5, [0 255 255]);
    
    % now the bit of code from drawformattedtext
    Screen('glPushMatrix', wpnt);
    Screen('glTranslate', wpnt, xc, yc, 0);
    if 1
        Screen('glScale', wpnt, 1, -1, 1);
    end
    Screen('glTranslate', wpnt, -xc, -yc, 0);
    Screen('DrawText', wpnt, txt, xp, yp, 0, [], 1);
    Screen('DrawDots', wpnt, [xp, yp],5, [0 255 0]);
    Screen('DrawDots', wpnt, [xc+6, yc],5, [255 255 0]);
    Screen('glPopMatrix', wpnt);

    Screen('Flip',wpnt);
    % verify we got the right bounding box
    imageArray=Screen('GetImage', wpnt,ClipRect(GrowRect(textbox,1,1),wrect));

    KbStrokeWait;
    sca
catch me
    sca
    rethrow(me)
end
```

**Comment by dcnieho** [comment] 2016-08-01 18:53
glRotate also does not produce the correct result, you can paste this in the last test code:
```
if 0
    Screen('glScale', wpnt, 1, -1, 1);
else
    Screen('glRotate', wpnt, 90, 0, 0, 1);
end
```

**Comment by kleinerm** [comment] 2016-08-05 19:40
Can you look into it? Whatever causes it would have to be resolved via tweaking of Matlab code in DrawFormattedText.m. If that isn't possible and the cause is the "new" text rendering plugin i'd just update the help text to say that accurate formatting isn't supported for such flipped text. The text renderer plugin does work differently from the old renderers, so could be that such global transforms don't work.

I can't even remember why we support this text flipping at all, given that one usually only wants to flip text when one wants to flip the rest of the stimulus as well, e.g., for presentation in fMRI setups or maybe haploscopes. There the PsychImaging() pipeline is a much better choice for flipping things anyway.

**Comment by dcnieho** [comment] 2016-08-05 21:10
It definitely seems to be something internal to the plugin, given the last test code i posted above. The middle of the text is correctly determined from a Screen('TextBounds'), but the flipped text behaves as if we're transforming with completely the wrong vertical center.

I do need this, for instance i have currently written some functions to make plots in PTB code. I need to rotate the y axis label :p. I'll try to see if there is reason to the madness, or if there is a simple thing that can be done at the FTGL side. Will get back to you with feedback if i have something.

**Comment by PK-HQ** [comment] 2016-08-18 07:27
I have an issue exactly, PTB-3.0.12, and the vert_flip option just causes text to display way off where it should be. Any solution yet?

**Comment by dcnieho** [comment] 2016-08-18 14:16
Thanks for writing in. Not yet. Make sure you get notified of posts to this
issue, as any updates will be discussed here. I'm determined to get to the
bottom of this issue, but it doesn't have such high priority for me, so it
may take a few months before a nice full day pops up where i can sit down
and kick its ass :p

**Comment by dcnieho** [comment] 2016-08-19 13:22
@kleinerm The problem is that the origin for the text rendering plugin is bottom-left, where PTB's is top-left. The below works correctly. Note the line where i calculate the vertical offset of the center of the text from the bottom of the screen instead of the top.  Well, it almost works correctly. There is a small vertical offset of the flipped text still--this is gone too when not using yPositionIsBaseline. I'm not sure how yPositionIsBaseline interacts with all this, there must be a small offset somewhere in the drawing code that goes the wrong way when flipped.

Is this something that is easily corrected? Applying any Screen('gl<transform>') to part of your stimulus now does different things to the text and to the rest of the stimulus. I'm happy to try and implement it, if you can give me a hint or two of how to approach that.

```
clear all
Screen('Preference','SkipSyncTests', 1);
Screen('Preference', 'TextRenderer', 1);

PsychDebugWindowConfiguration;

txt = 'test';
[xp, yp] = deal(500,500);

try
    InitializeMatlabOpenGL;
    [wpnt,wrect] = PsychImaging('OpenWindow', 0,255);
    
    [~,bbox] = Screen('TextBounds', wpnt, txt,0,0,1);    % this bounding box is pixel-precise and relative to baseline
    textbox = OffsetRect(bbox, xp, yp);
    [xc, yc] = RectCenter(textbox);
    yc = wrect(4)-yc;
    
    % draw text and dots without transformation matrices applied, see where
    % things should be showing up
    Screen('DrawText', wpnt, txt, xp, yp, [255 0 0], [], 1);
    
    % now the bit of code from drawformattedtext
    Screen('glPushMatrix', wpnt);
    Screen('glTranslate', wpnt, xc, yc, 0);
    if 1
        Screen('glScale', wpnt, 1, -1, 1);
    else
        Screen('glRotate', wpnt, 90, 0, 0, 1);
    end
    Screen('glTranslate', wpnt, -xc, -yc, 0);
    Screen('DrawText', wpnt, txt, xp, yp, 0, [], 1);
    Screen('glPopMatrix', wpnt);

    Screen('Flip',wpnt);
    % verify we got the right bounding box
    imageArray=Screen('GetImage', wpnt,ClipRect(GrowRect(textbox,1,1),wrect));

    KbStrokeWait;
    sca
catch me
    sca
    rethrow(me)
end
```

**Comment by dcnieho** [comment] 2016-08-22 12:13
This text drawing with the reversed y axis is only an issue with TextRenderer 1. For TextRenderer 0 (on windows), it works ok out of the box. Not perfect, but ok (as bounding box isn't accurate). Anyway, the point is that it is a problem specific to TextRenderer 1, which makes any matlab-side fix of DrawFormattedText require a check on each invocation which text renderer is used (it would probably be ok to cache the result, but the user could change it out from under us). I think the better solution is to look at the C-side of things. And as said, i'd be happy to do it. Is there a reason (0,0) of the coordinate system of the text plugin is in the bottom left instead of top left?

**Comment by dcnieho** [comment] 2016-08-22 19:24
Just a note: ok, this has further consequences. The PTB screen is a lefthanded coordinate system with positive rotations being clockwise. However, as for text drawing internally the origin is bottom-left (a righthanded coordinate system), Screen('glRotate',win,90) does counterclockwise rotation. So its not just flips that work different for text than for other stimuli, its also rotations. I have solved all this in matlab code, but as said, it requires which text renderer is active for it to work correctly. It may be better to solve this in the text renderer itself

**Comment by kleinerm** [comment] 2016-08-23 20:52
PTB's coordinate is a right-handed coordinate system, but one where origin top-left, x-axis right, y-axis down, z-axis into the screen, away from the viewer. That's because backwards compatibility. OpenGL's frame is usually x-axis right,y-axis up, and the text renderer plugin wraps FTGL which uses classic OpenGL reference, so we must remap.

I agree that this should probably done from within the plugin, but i don't have the time atm. Didn't read any of your writing, because my brain is 100% occupied with other complex stuff for probably at least another week. Otoh. DrawFormattedText is meant around to give basic text formatting on a primitive Screen('DrawText') renderer with the current plugin, so maybe adding bits of more fudge code to it is good enough. It is already a slow solution for more complex text formatting, so a bit more slowdown for such a special case seems to be ok.

Ideally we'd write a new text rendering plugin based on pango et al. for complex text formatting, where one is usually ok with sacrificing a lot of speed for complex typesetting functionality. DrawformattedText already does more than it should sanely do, and it is showing...

**Comment by dcnieho** [comment] 2016-08-24 09:34
No worries, please focus on what is currently in your head. Look at anything past this paragraph and reply to the below once you're ready for it. I'll fix up drawFormattedText shortly and send a pull request. You are right that a an extra query that only happens when drawing text flipped upside down is a reasonable cost for a function that is not meant to be fast. Thanks for explaining the coordinate system of PTB.

I have almost finished work on a DrawFormattedText2 function which is way more complex than DrawFormattedText. Its a stopgap measure until we implement Pango indeed. I have looked into providing Pango. Since Pango comes with and is accessible through Cairo, and Cairo can also be of use, it may be good to provide interfaces to both (both appear to be included with GStreamer). Cairo is of use for instance when drawing line consisting of several segments that need to be joined together with rounded or mitered, etc, joints. But its also suitable for many other higher-level drawing commands, e.g., polygon clipping and many other things.

This will not happen this year, but I will take it on. I'm in a bit more of a technical role now, where this work would fit.

To finish my DrawFormattedText2 function, I need to do a bit more work on the Screen('TextBounds'). To do reasonable linespacing, I need access to the height argument returned by Screen('DrawText'), without actually drawing any text. It may work to simply draw an empty string, but perhaps having text height as an output argument of Screen('TextBounds') (or a separate Screen('TextHeight')) would make more sense. so I'll be diggin my nose into the FTGL plugin anyway, and could see if i can figure out the remapping there.

**Comment by dcnieho** [comment] 2016-08-30 13:54
When #366 is in (the C changes), this can be closed.

In reference to my previous message, I see that Screen('TextBounds') does return text height (why did i not see that?!), so no need to change anything in the interface. Its return values do not change with font size changes however, so I'll have look into that.

Whats your views on Cairo, if we're implementing Pango anyway?

**Comment by kleinerm** [comment] 2016-08-30 14:05
I added that height on your request a while ago.

Cairo not so excited about that. It could be provided as a 3rd party project, like the Horde3D engine wrapper for PTB, not part of the official PTB, or maintained/guaranteed to work long-term by me. I like to keep external dependencies to a minimum. Cairo itself is widely used and popular, but it uses its own rendering backends and i don't know how well it would interact with PTB's existing OpenGL approach. Whenever possible we want to use OpenGL + useful OpenGL extensions to achieve drawing tasks, possibly things like OpenCL, so we don't deal with compatibility issues, different reference frames, different performance, accuracy etc. E.g., OpenGL allows for high precision drawing with more than 8 bpc, but i don't know if Cairo does that by default or in default builds, or with high performance, or in a useful way on small devices like RaspberryPi. Our text renderer btw. is the exception wrt. accuracy, it only does 8 bpc atm., but changing that would at least be possible due to its OpenGL nature.

**Comment by dcnieho** [comment] 2016-08-30 14:31
That was the advance, textheight is from earlier this year i see, at the same time as when you made the changes to support accurate text cursor info and such. Anyway, good to have it too!

I understand your position about Cairo. I for one would be happy to have it, but entangling it too deeply with PTB would increase your work and potential headaches by more than it offers. I like you proposed way of dealing with it. I guess the same goes for a text renderer plugin such as pango. Due to the plugin nature, its nice separated from core PTB and needs no maintenance when PTB moves. Smart!

**Comment by kleinerm** [comment] 2016-08-30 15:32
With Pango we have to see. It may add enough value to make it worth keeping in the distro. And users know to expect quite difference performance/accuracy/quality tradeoffs if they intentionally select that plugin. We'll see it when its there.

**Closed** 2016-09-28 12:56 UTC
