### ISSUE TITLE
UpdatePsychtoolbox failed in upgrating.

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#413] opened 2017-05-09 02:51 UTC
Run `UpdatePsychtoolbox` in matlab, or run `svn update` in commandline, both report such information without upgrading:
> At revision 5583.

While `PsychtoolboxVersion` report my local copy is 3.0.13 (on some other computer, it is 3.0.12) which is certainly not the newest one (3.0.14).

I'll have to re-install for an upgrade. But after re-install, subversion still report the revision is **5583**. There should be something wrong in svn database, please consider fix it.

**Comment by kleinerm** [comment] 2017-05-19 00:59
I think it can be resolved by redownloading once. At least that helped on MS Windows here. Not sure what the cause is, but it is generally out of our control, as it would either be some SVN bug or some problem at GitHub.

**Closed by kleinerm** 2017-05-19 00:59 UTC
